const STORAGE_KEY='elderwildStudio.v1';
const state=loadState();
let editing={type:null,id:null};
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const slug=s=>String(s||'').trim().toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'');

function loadState(){try{const v=JSON.parse(localStorage.getItem(STORAGE_KEY));if(v&&Array.isArray(v.items)&&Array.isArray(v.enemies))return v}catch{}return{items:[],enemies:[]}}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));renderAll()}

function renderAll(){renderItems();renderEnemies()}
function empty(el){el.innerHTML='';el.append($('#emptyTemplate').content.cloneNode(true))}
function renderItems(){const q=$('#itemSearch').value.trim().toLowerCase();const rows=state.items.filter(x=>`${x.name} ${x.id} ${x.type} ${x.rarity}`.toLowerCase().includes(q));const el=$('#itemList');if(!rows.length)return empty(el);el.innerHTML=rows.sort((a,b)=>a.name.localeCompare(b.name)).map(x=>`<article class="card entry-card"><div><h3>${esc(x.name)}</h3><div class="entry-meta">${esc(x.id)} · ${esc(x.type||'Item')} · ${esc(x.rarity||'Common')}<br>Value: ${Number(x.value)||0}${x.stackable?' · Stackable':''}</div></div><div class="entry-actions"><button class="small" data-action="edit" data-type="item" data-id="${esc(x.id)}">Edit</button><button class="small" data-action="duplicate" data-type="item" data-id="${esc(x.id)}">Duplicate</button><button class="small danger" data-action="delete" data-type="item" data-id="${esc(x.id)}">Delete</button></div></article>`).join('')}
function renderEnemies(){const q=$('#enemySearch').value.trim().toLowerCase();const rows=state.enemies.filter(x=>`${x.name} ${x.id} ${x.biome} ${x.tier}`.toLowerCase().includes(q));const el=$('#enemyList');if(!rows.length)return empty(el);el.innerHTML=rows.sort((a,b)=>(+a.tier||0)-(+b.tier||0)||a.name.localeCompare(b.name)).map(x=>`<article class="card entry-card"><div><h3>${esc(x.name)}</h3><div class="entry-meta">${esc(x.id)} · Tier ${Number(x.tier)||1} · ${esc(x.biome||'Unassigned')}<br>HP ${Number(x.hp)||1} · ATK ${Number(x.attack)||1} · STR ${Number(x.strength)||1} · DEF ${Number(x.defense)||1} · ${x.drops?.length||0} drops</div></div><div class="entry-actions"><button class="small" data-action="edit" data-type="enemy" data-id="${esc(x.id)}">Edit</button><button class="small" data-action="duplicate" data-type="enemy" data-id="${esc(x.id)}">Duplicate</button><button class="small danger" data-action="delete" data-type="enemy" data-id="${esc(x.id)}">Delete</button></div></article>`).join('')}

const input=(name,label,value='',type='text',full=false,min='')=>`<div class="field ${full?'full-span':''}"><label for="f_${name}">${label}</label><input id="f_${name}" name="${name}" type="${type}" value="${esc(value)}" ${min!==''?`min="${min}"`:''}></div>`;
const select=(name,label,value,opts)=>`<div class="field"><label for="f_${name}">${label}</label><select id="f_${name}" name="${name}">${opts.map(o=>`<option ${o===value?'selected':''}>${esc(o)}</option>`).join('')}</select></div>`;
function openEditor(type,obj=null){editing={type,id:obj?.id||null};$('#editorTitle').textContent=`${obj?'Edit':'New'} ${type==='item'?'Item':'Enemy'}`;const f=$('#editorFields');if(type==='item'){
 const x=obj||{name:'',id:'',description:'',type:'Equipment',slot:'None',rarity:'Common',value:0,stackable:false,attack:0,strength:0,defense:0,healing:0,attackSpeedTicks:4,requiredLevel:1,image:''};
 f.innerHTML=input('name','Name',x.name,'text',true)+input('id','Internal ID',x.id)+select('type','Type',x.type,['Equipment','Food','Material','Currency','Quest','Other'])+select('slot','Equipment Slot',x.slot||'None',['None','Weapon','Head','Body','Legs','Hands','Feet','Shield','Necklace','Ring','Cape'])+select('rarity','Rarity',x.rarity||'Common',['Common','Uncommon','Rare','Epic','Legendary','Ultra Rare'])+input('value','Value',x.value,'number',false,0)+input('requiredLevel','Required Level',x.requiredLevel,'number',false,1)+input('attack','Attack Bonus',x.attack,'number')+input('strength','Strength Bonus',x.strength,'number')+input('defense','Defense Bonus',x.defense,'number')+input('healing','Healing',x.healing,'number',false,0)+input('attackSpeedTicks','Attack Speed (ticks)',x.attackSpeedTicks,'number',false,1)+input('image','Image Filename',x.image,'text',true)+`<div class="field full-span"><label>Description</label><textarea name="description">${esc(x.description)}</textarea></div><div class="field full-span"><label class="check-row"><input name="stackable" type="checkbox" ${x.stackable?'checked':''}> Stackable</label></div>`;
 }else{
 const x=obj||{name:'',id:'',biome:'Forest',tier:1,hp:10,attack:1,strength:1,defense:1,attackSpeedTicks:4,respawnSeconds:20,slayerLevel:1,sprite:'',drops:[]};
 f.innerHTML=input('name','Name',x.name,'text',true)+input('id','Internal ID',x.id)+select('biome','Biome',x.biome||'Forest',['Forest','Volcano','Void','Snow','Other'])+input('tier','Tier',x.tier,'number',false,1)+input('hp','HP',x.hp,'number',false,1)+input('attack','Attack',x.attack,'number',false,1)+input('strength','Strength',x.strength,'number',false,1)+input('defense','Defense',x.defense,'number',false,1)+input('attackSpeedTicks','Attack Speed (ticks)',x.attackSpeedTicks,'number',false,1)+input('respawnSeconds','Respawn (seconds)',x.respawnSeconds,'number',false,0)+input('slayerLevel','Slayer Requirement',x.slayerLevel,'number',false,1)+input('sprite','Sprite Filename',x.sprite,'text',true)+`<div class="drop-section"><div class="dialog-header"><h2>Drops</h2><button type="button" id="addDropBtn" class="small primary">+ Add Drop</button></div><div id="dropRows"></div><small>Chance accepts denominators: 1 = always, 100 = 1/100, 1000 = 1/1,000.</small></div>`;
 renderDrops(x.drops||[]);
 }
 const name=f.querySelector('[name=name]'),id=f.querySelector('[name=id]');let touched=!!obj;name.addEventListener('input',()=>{if(!touched)id.value=slug(name.value)});id.addEventListener('input',()=>touched=true);$('#editorDialog').showModal();
}
function renderDrops(drops){const el=$('#dropRows');el.innerHTML=drops.map((d,i)=>`<div class="drop-row"><input name="dropItem" placeholder="item_id" value="${esc(d.item)}"><input name="dropChance" type="number" min="1" placeholder="1/x" value="${Number(d.chance)||1}"><input name="dropQty" type="number" min="1" placeholder="Qty" value="${Number(d.quantity)||1}"><button type="button" class="small danger remove-drop" data-index="${i}">Remove</button></div>`).join('');}
function readForm(){const fd=new FormData($('#editorForm'));const n=k=>Number(fd.get(k))||0;if(editing.type==='item')return{name:String(fd.get('name')||'').trim(),id:slug(fd.get('id')),description:String(fd.get('description')||''),type:String(fd.get('type')),slot:String(fd.get('slot')),rarity:String(fd.get('rarity')),value:n('value'),requiredLevel:n('requiredLevel')||1,attack:n('attack'),strength:n('strength'),defense:n('defense'),healing:n('healing'),attackSpeedTicks:n('attackSpeedTicks')||4,image:String(fd.get('image')||'').trim(),stackable:fd.get('stackable')==='on'};const items=[...document.querySelectorAll('[name=dropItem]')],chances=[...document.querySelectorAll('[name=dropChance]')],qty=[...document.querySelectorAll('[name=dropQty]')];return{name:String(fd.get('name')||'').trim(),id:slug(fd.get('id')),biome:String(fd.get('biome')),tier:n('tier')||1,hp:n('hp')||1,attack:n('attack')||1,strength:n('strength')||1,defense:n('defense')||1,attackSpeedTicks:n('attackSpeedTicks')||4,respawnSeconds:n('respawnSeconds'),slayerLevel:n('slayerLevel')||1,sprite:String(fd.get('sprite')||'').trim(),drops:items.map((x,i)=>({item:slug(x.value),chance:Number(chances[i].value)||1,quantity:Number(qty[i].value)||1})).filter(x=>x.item)}}

$('.tabs').addEventListener('click',e=>{const b=e.target.closest('.tab');if(!b)return;document.querySelectorAll('.tab,.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active')});
$('#newItemBtn').onclick=()=>openEditor('item');$('#newEnemyBtn').onclick=()=>openEditor('enemy');$('#closeDialogBtn').onclick=$('#cancelBtn').onclick=()=>$('#editorDialog').close();
$('#itemSearch').oninput=renderItems;$('#enemySearch').oninput=renderEnemies;
document.body.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const arr=b.dataset.type==='item'?state.items:state.enemies;const i=arr.findIndex(x=>x.id===b.dataset.id);if(i<0)return;if(b.dataset.action==='edit')openEditor(b.dataset.type,arr[i]);if(b.dataset.action==='duplicate'){const copy=structuredClone(arr[i]);copy.name+=' Copy';copy.id=uniqueId(slug(copy.name),arr);arr.push(copy);saveState()}if(b.dataset.action==='delete'&&confirm(`Delete ${arr[i].name}?`)){arr.splice(i,1);saveState()}});
function uniqueId(base,arr,old=null){let id=base||'unnamed';let n=2;while(arr.some(x=>x.id===id&&x.id!==old))id=`${base}_${n++}`;return id}
$('#editorForm').addEventListener('submit',e=>{e.preventDefault();const obj=readForm();if(!obj.name){alert('Name is required.');return}const arr=editing.type==='item'?state.items:state.enemies;obj.id=uniqueId(obj.id||slug(obj.name),arr,editing.id);const i=arr.findIndex(x=>x.id===editing.id);if(i>=0)arr[i]=obj;else arr.push(obj);saveState();$('#editorDialog').close()});
$('#editorFields').addEventListener('click',e=>{if(e.target.id==='addDropBtn'){const current=[...document.querySelectorAll('#dropRows .drop-row')].map(r=>({item:r.querySelector('[name=dropItem]').value,chance:r.querySelector('[name=dropChance]').value,quantity:r.querySelector('[name=dropQty]').value}));current.push({item:'',chance:1,quantity:1});renderDrops(current)}const b=e.target.closest('.remove-drop');if(b)b.parentElement.remove()});
$('#exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify({format:'ElderwildStudio',version:1,exportedAt:new Date().toISOString(),...state},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='elderwild_content.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
$('#importInput').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const d=JSON.parse(await file.text());if(!Array.isArray(d.items)||!Array.isArray(d.enemies))throw Error();if(!confirm(`Import ${d.items.length} items and ${d.enemies.length} enemies? This replaces local data.`))return;state.items=d.items;state.enemies=d.enemies;saveState();alert('Import complete.')}catch{alert('That file is not a valid Elderwild Studio export.')}finally{e.target.value=''}};
$('#clearBtn').onclick=()=>{if(confirm('Delete ALL locally saved items and enemies?')){state.items=[];state.enemies=[];saveState()}};
renderAll();
