import{Game,xpForLevel}from'./game.js';
import{SKILLS}from'./data.js';
import{ITEM_TYPES}from'./items.js';
import{ENEMIES,COMBAT_STYLES}from'./combat.js';

const view=document.querySelector('#view');
const game=new Game(render);
let currentView='home';
let selectedSkill='Fishing';

document.querySelectorAll('.nav-button').forEach(btn=>btn.addEventListener('click',()=>{currentView=btn.dataset.view;document.querySelectorAll('.nav-button').forEach(b=>b.classList.toggle('active',b===btn));render()}));
document.querySelector('#stop-activity').addEventListener('click',()=>game.stopActivity());

function esc(value){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function skillCard(skill){const next=skill.level>=99?skill.xp:xpForLevel(skill.level+1);const base=xpForLevel(skill.level);const pct=skill.level>=99?100:Math.max(0,Math.min(100,(skill.xp-base)/(next-base)*100));return `<button class="card" data-skill="${esc(skill.name)}"><div class="skill-row"><span><span class="skill-icon">${skill.icon}</span> ${esc(skill.name)}</span><strong>${skill.level}</strong></div><div class="xpbar"><div class="xpfill" style="width:${pct}%"></div></div><small class="muted">${Math.floor(skill.xp).toLocaleString()} XP</small></button>`}
function itemStats(item){const bits=[];if(item.attack)bits.push(`Atk ${item.attack>=0?'+':''}${item.attack}`);if(item.strength)bits.push(`Str ${item.strength>=0?'+':''}${item.strength}`);if(item.defense)bits.push(`Def ${item.defense>=0?'+':''}${item.defense}`);if(item.hp)bits.push(`HP ${item.hp>=0?'+':''}${item.hp}`);if(item.healing)bits.push(`Heals ${item.healing}`);return bits.join(' · ')}

function renderHome(){return `<section class="hero"><h2>Welcome, ${esc(game.state.playerName)}</h2><p>ScapeRunner is being rebuilt here as a browser-native game. Core progression still runs on the original 600 ms tick.</p></section><section class="panel"><h2>Progress</h2><div class="grid">${SKILLS.slice(0,6).map(s=>{const sk=game.getSkill(s.name);return `<div class="card"><strong>${sk.icon} ${esc(sk.name)}</strong><p>Level ${sk.level}</p><small class="muted">${sk.actions||0} actions</small></div>`}).join('')}</div></section>`}
function renderSkills(){if(selectedSkill){const skill=game.getSkill(selectedSkill);const activities=skill.activities.length?skill.activities.map(a=>`<div class="activity-card ${skill.level<a.level?'locked':''}"><div><strong>${a.icon} ${esc(a.name)}</strong><div class="muted">Level ${a.level} · ${a.xp} XP · ${(a.ticks*.6).toFixed(1)}s${a.item?` · ${esc(a.item)}`:''}</div></div><button class="action-button" data-activity="${esc(a.name)}" ${skill.level<a.level?'disabled':''}>Train</button></div>`).join(''):'<p class="muted">This skill data has not been migrated yet.</p>';return `<button class="action-button" id="back-skills">← All skills</button><section class="panel"><h2>${skill.icon} ${esc(skill.name)} — Level ${skill.level}</h2><p>${Math.floor(skill.xp).toLocaleString()} XP</p><div class="activity-list">${activities}</div></section>`}return `<section class="panel"><h2>Skills</h2><div class="grid">${SKILLS.map(s=>skillCard(game.getSkill(s.name))).join('')}</div></section>`}
function renderInventory(){const items=game.state.inventory.filter(i=>i.quantity>0);const used=game.usedSlots();return `<section class="panel"><div class="skill-row"><h2>Inventory</h2><strong>${used} / ${game.state.slotCapacity} slots</strong></div>${items.length?`<div class="inventory-grid">${items.map((item,index)=>`<div class="inventory-slot"><div class="skill-row"><strong>${item.icon||'•'} ${esc(item.name)}</strong><span class="qty">× ${item.quantity}</span></div><small class="muted">${esc(item.type)}${item.type===ITEM_TYPES.EQUIPMENT?` · ${esc(item.slot)}`:''} · ${item.value.toLocaleString()} coins</small>${itemStats(item)?`<small>${esc(itemStats(item))}</small>`:''}${item.type===ITEM_TYPES.EQUIPMENT&&item.quantity>=2&&item.upgradeLevel<10?`<button class="action-button combine-button" data-combine="${index}">Combine 2 → +${item.upgradeLevel+1}</button>`:''}</div>`).join('')}</div>`:'<p class="muted">Your inventory is empty.</p>'}</section>`}
function renderSettings(){return `<section class="panel"><h2>Settings</h2><div class="settings-row"><input id="name-input" maxlength="24" value="${esc(game.state.playerName)}"><button id="save-name" class="action-button">Save name</button></div><p class="muted">Progress saves automatically in localStorage. Older v1 web saves migrate automatically.</p><button id="reset-save" class="danger-button">Reset web save</button></section>`}
function renderCombat(){const c=game.state.combat;const enemy=c.active?ENEMIES.find(e=>e.name===c.enemyName):null;const styles=Object.values(COMBAT_STYLES).map(s=>`<button class="action-button ${c.style===s?'active':''}" data-style="${s}">${s}</button>`).join('');if(enemy){const enemyPct=Math.max(0,c.enemyHP/enemy.hp*100);const playerMax=Math.max(1,game.getSkill('HP').level);const playerPct=Math.max(0,c.playerHP/playerMax*100);return `<section class="panel"><h2>Combat</h2><div class="settings-row">${styles}</div><div class="card"><h3>${enemy.icon} ${esc(enemy.name)}</h3><div class="muted">Enemy HP ${c.enemyHP} / ${enemy.hp}</div><div class="xpbar"><div class="xpfill" style="width:${enemyPct}%"></div></div><div class="muted">Your HP ${c.playerHP} / ${playerMax}</div><div class="xpbar"><div class="xpfill" style="width:${playerPct}%"></div></div><p>${esc(c.lastLog)}</p><button class="danger-button" id="run-away">Run away</button></div></section>`}return `<section class="panel"><h2>Combat</h2><div class="settings-row">${styles}</div><p class="muted">${esc(c.lastLog)}</p><div class="activity-list">${ENEMIES.map(e=>{const locked=e.requirement&&game.getSkill(e.requirement.skill).level<e.requirement.level;return `<div class="activity-card ${locked?'locked':''}"><div><strong>${e.icon} ${esc(e.name)}</strong><div class="muted">HP ${e.hp} · Atk ${e.attack} · Str ${e.strength} · Def ${e.defense} · ${(e.attackSpeed*.6).toFixed(1)}s${e.requirement?` · Requires ${esc(e.requirement.skill)} ${e.requirement.level}`:''}</div><small>Weak to ${e.weakness}</small></div><button class="action-button" data-enemy="${esc(e.name)}" ${locked?'disabled':''}>Fight</button></div>`}).join('')}</div></section>`}

function bindView(){document.querySelectorAll('[data-skill]').forEach(el=>el.addEventListener('click',()=>{selectedSkill=el.dataset.skill;render()}));document.querySelector('#back-skills')?.addEventListener('click',()=>{selectedSkill=null;render()});document.querySelectorAll('[data-activity]').forEach(el=>el.addEventListener('click',()=>game.startActivity(selectedSkill,el.dataset.activity)));document.querySelectorAll('[data-combine]').forEach(el=>el.addEventListener('click',()=>{const item=game.state.inventory[Number(el.dataset.combine)];if(item)game.combineEquipment(item)}));document.querySelectorAll('[data-enemy]').forEach(el=>el.addEventListener('click',()=>game.startFight(el.dataset.enemy)));document.querySelectorAll('[data-style]').forEach(el=>el.addEventListener('click',()=>game.setCombatStyle(el.dataset.style)));document.querySelector('#run-away')?.addEventListener('click',()=>game.stopFight());document.querySelector('#save-name')?.addEventListener('click',()=>game.setName(document.querySelector('#name-input').value));document.querySelector('#reset-save')?.addEventListener('click',()=>{if(confirm('Reset all web progress?'))game.reset()})}
function renderActivity(){const bar=document.querySelector('#activity-bar');const a=game.state.activity;if(!a){bar.classList.add('hidden');return}bar.classList.remove('hidden');document.querySelector('#activity-name').textContent=`${a.skillName}: ${a.activityName}`;document.querySelector('#activity-status').textContent=`Tick ${a.tick} / ${a.totalTicks}`;document.querySelector('#activity-progress').style.width=`${a.tick/a.totalTicks*100}%`}
function render(){document.querySelector('#player-name').textContent=game.state.playerName;document.querySelector('#total-level').textContent=`Total ${game.totalLevel()}`;view.innerHTML=currentView==='home'?renderHome():currentView==='skills'?renderSkills():currentView==='combat'?renderCombat():currentView==='inventory'?renderInventory():renderSettings();bindView();renderActivity()}

render();
