import{Game,xpForLevel}from'./game.js';
import{SKILLS}from'./data.js';

const view=document.querySelector('#view');
const game=new Game(render);
let currentView='home';
let selectedSkill='Fishing';

document.querySelectorAll('.nav-button').forEach(btn=>btn.addEventListener('click',()=>{currentView=btn.dataset.view;document.querySelectorAll('.nav-button').forEach(b=>b.classList.toggle('active',b===btn));render()}));
document.querySelector('#stop-activity').addEventListener('click',()=>game.stopActivity());

function esc(value){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function skillCard(skill){const next=skill.level>=99?skill.xp:xpForLevel(skill.level+1);const base=xpForLevel(skill.level);const pct=skill.level>=99?100:Math.max(0,Math.min(100,(skill.xp-base)/(next-base)*100));return `<button class="card" data-skill="${esc(skill.name)}"><div class="skill-row"><span><span class="skill-icon">${skill.icon}</span> ${esc(skill.name)}</span><strong>${skill.level}</strong></div><div class="xpbar"><div class="xpfill" style="width:${pct}%"></div></div><small class="muted">${Math.floor(skill.xp).toLocaleString()} XP</small></button>`}

function renderHome(){return `<section class="hero"><h2>Welcome, ${esc(game.state.playerName)}</h2><p>This is the first browser-native migration slice of ScapeRunner. The save lives in your browser and the game loop uses the original 600 ms tick.</p></section><section class="panel"><h2>Progress</h2><div class="grid">${SKILLS.slice(0,6).map(s=>{const sk=game.getSkill(s.name);return `<div class="card"><strong>${sk.icon} ${esc(sk.name)}</strong><p>Level ${sk.level}</p><small class="muted">${sk.actions||0} actions</small></div>`}).join('')}</div></section>`}
function renderSkills(){if(selectedSkill){const skill=game.getSkill(selectedSkill);const activities=skill.activities.length?skill.activities.map(a=>`<div class="activity-card ${skill.level<a.level?'locked':''}"><div><strong>${a.icon} ${esc(a.name)}</strong><div class="muted">Level ${a.level} · ${a.xp} XP · ${(a.ticks*.6).toFixed(1)}s${a.item?` · ${esc(a.item)}`:''}</div></div><button class="action-button" data-activity="${esc(a.name)}" ${skill.level<a.level?'disabled':''}>Train</button></div>`).join(''):'<p class="muted">This skill data has not been migrated yet.</p>';return `<button class="action-button" id="back-skills">← All skills</button><section class="panel"><h2>${skill.icon} ${esc(skill.name)} — Level ${skill.level}</h2><p>${Math.floor(skill.xp).toLocaleString()} XP</p><div class="activity-list">${activities}</div></section>`}return `<section class="panel"><h2>Skills</h2><div class="grid">${SKILLS.map(s=>skillCard(game.getSkill(s.name))).join('')}</div></section>`}
function renderInventory(){const items=Object.entries(game.state.inventory).filter(([,q])=>q>0);return `<section class="panel"><h2>Inventory</h2>${items.length?`<div class="inventory-grid">${items.map(([name,qty])=>`<div class="inventory-slot"><strong>${esc(name)}</strong><div class="qty">× ${qty}</div></div>`).join('')}</div>`:'<p class="muted">Your inventory is empty.</p>'}</section>`}
function renderSettings(){return `<section class="panel"><h2>Settings</h2><div class="settings-row"><input id="name-input" maxlength="24" value="${esc(game.state.playerName)}"><button id="save-name" class="action-button">Save name</button></div><p class="muted">Progress saves automatically in localStorage.</p><button id="reset-save" class="danger-button">Reset web save</button></section>`}
function renderCombat(){return `<section class="panel"><h2>Combat</h2><p class="muted">CombatManager, enemies, drops, equipment, auto-eat, and offline combat are next migration systems. The page is reserved so the navigation structure already matches ScapeRunner.</p></section>`}

function bindView(){document.querySelectorAll('[data-skill]').forEach(el=>el.addEventListener('click',()=>{selectedSkill=el.dataset.skill;render()}));document.querySelector('#back-skills')?.addEventListener('click',()=>{selectedSkill=null;render()});document.querySelectorAll('[data-activity]').forEach(el=>el.addEventListener('click',()=>game.startActivity(selectedSkill,el.dataset.activity)));document.querySelector('#save-name')?.addEventListener('click',()=>game.setName(document.querySelector('#name-input').value));document.querySelector('#reset-save')?.addEventListener('click',()=>{if(confirm('Reset all web progress?'))game.reset()})}
function renderActivity(){const bar=document.querySelector('#activity-bar');const a=game.state.activity;if(!a){bar.classList.add('hidden');return}bar.classList.remove('hidden');document.querySelector('#activity-name').textContent=`${a.skillName}: ${a.activityName}`;document.querySelector('#activity-status').textContent=`Tick ${a.tick} / ${a.totalTicks}`;document.querySelector('#activity-progress').style.width=`${a.tick/a.totalTicks*100}%`}
function render(){document.querySelector('#player-name').textContent=game.state.playerName;document.querySelector('#total-level').textContent=`Total ${game.totalLevel()}`;view.innerHTML=currentView==='home'?renderHome():currentView==='skills'?renderSkills():currentView==='combat'?renderCombat():currentView==='inventory'?renderInventory():renderSettings();bindView();renderActivity()}

render();
