import{getItem,ITEM_TYPES}from'./items.js';import{HAND_ROWS,EXPANDED_ROWS,REGISTRY_ORDER,BOSS_ROWS}from'./combat-data-core.js';import{EQUIPMENT_DROPS_ONE}from'./combat-drops-1.js';import{EQUIPMENT_DROPS_TWO}from'./combat-drops-2.js';
export const COMBAT_STYLES={ATTACK:'Attack',STRENGTH:'Strength',DEFENSE:'Defense'};
export const AREA_INFO=[{tier:1,name:'Greenvale',description:'Bright grasslands, lakes, and castle countryside.'},{tier:2,name:'Mirewood',description:'Gloomy, overgrown swamp and dead forest.'},{tier:3,name:'Frostpeak',description:'Snowy mountains and frozen mines.'},{tier:4,name:'Emberfall',description:'Volcanic wasteland and lava fields.'},{tier:5,name:'Sandswept Ruins',description:'Ancient desert civilization and buried temples.'},{tier:6,name:'The Astral Reach',description:'Floating islands, purple skies, and arcane ruins.'},{tier:7,name:'The Umbral Expanse',description:'Corrupted realm beneath the black sun.'}];
function makeEnemy([name,icon,tier,hp,attack,strength,defense,attackSpeed,drops,requirement]){return{name,icon,tier,hp,attack,strength,defense,attackSpeed,drops:drops.map(([item,chance,min,max])=>({item,chance,min,max})),requirement:requirement||null,weakness:null,traits:[]}}
function makeExpanded([name,icon,tier,hp,attack,strength,defense,attackSpeed,common,rare,superRare,megaRare,requirement]){const drops=[{item:'Coins',chance:.8,min:Math.max(2,Math.trunc(hp/2)),max:Math.max(5,hp)},{item:common,chance:.65,min:1,max:3},{item:rare,chance:.01,min:1,max:1}];if(superRare)drops.push({item:superRare,chance:.001,min:1,max:1});if(megaRare)drops.push({item:megaRare,chance:.0001,min:1,max:1});return{name,icon,tier,hp,attack,strength,defense,attackSpeed,drops,requirement:requirement||null,weakness:null,traits:[]}}
const handMap=new Map(HAND_ROWS.map(row=>{const e=makeEnemy(row);return[e.name,e]})),expandedMap=new Map(EXPANDED_ROWS.map(row=>{const e=makeExpanded(row);return[e.name,e]}));
export const ENEMIES=REGISTRY_ORDER.map(name=>handMap.get(name)||expandedMap.get(name));
for(const[name,icon,tier,hp,attack,strength,defense,attackSpeed,primary,secondary]of BOSS_ROWS)ENEMIES.push({name,icon,tier,hp,attack,strength,defense,attackSpeed,requirement:null,weakness:null,traits:[],drops:[{item:'Coins',chance:1,min:Math.max(10,Math.trunc(hp/2)),max:Math.max(25,hp)},{item:primary,chance:.02,min:1,max:1},{item:secondary,chance:.004,min:1,max:1}]});
const enemyByName=new Map(ENEMIES.map(e=>[e.name,e]));function addEquipmentDrop([enemyName,item,chance]){const enemy=enemyByName.get(enemyName);if(enemy)enemy.drops.push({item,chance,min:1,max:1})}EQUIPMENT_DROPS_ONE.forEach(addEquipmentDrop);EQUIPMENT_DROPS_TWO.forEach(addEquipmentDrop);
const SHARED_POOLS={1:['Bones','Feathers','Animal Hide','Monster Claw','Logs'],2:['Bones','Spider Silk','Wolf Pelt','Iron Ore','Enchanted Leaf','Bog Pearl','Ember Core'],3:['Cursed Bone','Monster Fang','Werewolf Pelt','Manticore Hide','Ancient Bone','Moonstone Fragment','Shadow Silk'],4:['Mithril Ore','Mithril Bar','Runic Bar','Harpy Feather','Frostfang Scale','Wyrm Fang','Void Essence'],5:['Adamantite Ore','Runite Ore','Dragon Scale','Obsidian Heart','Crystal Fang','Celestial Shard','Ember Core'],6:['Runite Ore','Runic Bar','Dragon Scale','Ancient Dragon Scale','Void Essence','Astral Dust','God Fragment'],7:['Ancient Dragon Scale','Void Essence','Astral Dust','GodFragment','Celestial Shard']},SHARED_CHANCE={1:.15,2:.08,3:.04,4:.02,5:.01,6:.005,7:.002};
// Correct the typo-safe Tier 7 pool entry to the authoritative item name.
SHARED_POOLS[7][3]='God Fragment';
ENEMIES.forEach((enemy,index)=>{const pool=SHARED_POOLS[enemy.tier],desired=1+(index%3),start=(index*2)%pool.length;let added=0;for(let attempts=0;attempts<pool.length*2&&added<desired;attempts++){const item=pool[(start+attempts)%pool.length];if(enemy.drops.some(d=>d.item===item))continue;enemy.drops.push({item,chance:SHARED_CHANCE[enemy.tier],min:1,max:enemy.tier<=2?3:2});added++}});
const MAX_POWER={1:24,2:55,3:95,4:155,5:230,6:340,7:Number.MAX_SAFE_INTEGER};for(const enemy of ENEMIES)for(const drop of enemy.drops){const item=getItem(drop.item);if(item.type!==ITEM_TYPES.EQUIPMENT)continue;const power=item.attack+item.strength+item.defense+item.hp;if(power>MAX_POWER[enemy.tier])drop.chance=Math.min(drop.chance,.0001)}
const TRAIT_PROFILES=[[],['Armored'],['Accurate'],['Regenerative'],['Frenzied'],['Armored','Accurate'],['Armored','Regenerative'],['Accurate','Frenzied'],['Regenerative','Frenzied'],['Armored','Accurate','Frenzied'],['Armored','Accurate','Regenerative']],styleCycle=[COMBAT_STYLES.ATTACK,COMBAT_STYLES.STRENGTH,COMBAT_STYLES.DEFENSE],combatLevel=e=>Math.max(1,Math.trunc((e.attack+e.defense+e.strength+e.hp)/4));[...ENEMIES].sort((a,b)=>a.tier-b.tier||combatLevel(a)-combatLevel(b)||a.name.localeCompare(b.name)).forEach((enemy,index)=>{enemy.traits=[...TRAIT_PROFILES[index%TRAIT_PROFILES.length]];enemy.weakness=styleCycle[index%styleCycle.length]});
export const ENEMY_COUNT=ENEMIES.length;
export function hasTrait(enemy,trait){return enemy.traits?.includes(trait)||false}
export function enemyAttackSpeed(enemy){return hasTrait(enemy,'Frenzied')?Math.max(1,Math.floor(enemy.attackSpeed*.9)):enemy.attackSpeed}
export function enemyAttackLevel(enemy){return hasTrait(enemy,'Accurate')?Math.ceil(enemy.attack*1.1):enemy.attack}
export function enemyDefenseLevel(enemy){return hasTrait(enemy,'Armored')?Math.ceil(enemy.defense*1.15):enemy.defense}
export function reduceEnemyIncoming(enemy,damage){return hasTrait(enemy,'Armored')&&damage>0?Math.max(1,Math.floor(damage*.85)):damage}
export function enemyRegenAmount(enemy){return hasTrait(enemy,'Regenerative')?Math.max(1,Math.floor(enemy.hp/100)):0}
export function traitDescription(trait){return{Armored:'Takes 15% less damage',Accurate:'Has +10% hit chance',Regenerative:'Regains 1% max HP when it lands an attack',Frenzied:'Attacks up to 10% faster'}[trait]||trait}
export function hitChance(attack,defense){if(attack<=0&&defense<=0)return 1;attack=Math.max(0,attack);defense=Math.max(0,defense);return Math.max(.05,Math.min(.95,attack/(attack+defense||1)))}
export function maxHit(strength){return Math.max(1,Math.floor(strength/3)+1)}
export function rollHit(attack,defense,max){return Math.random()<hitChance(attack,defense)?1+Math.floor(Math.random()*Math.max(1,max)):0}
export function weaknessAttack(enemy,style,attack){return enemy.weakness===style?Math.ceil(attack*1.25):attack}
export function weaknessDamage(enemy,style,damage){return enemy.weakness===style?Math.max(1,Math.ceil(damage*1.25)):damage}
export function styledAttack(level,style){return style===COMBAT_STYLES.ATTACK?Math.ceil(level*1.10):level}
export function styledStrength(level,style){return style===COMBAT_STYLES.STRENGTH?Math.ceil(level*1.15):level}
export function styledDefense(level,style){return style===COMBAT_STYLES.DEFENSE?Math.ceil(level*1.15):level}
export function reduceIncoming(style,damage){return style===COMBAT_STYLES.DEFENSE?Math.max(0,Math.floor(damage*.90)):damage}
export function randomQuantity(min,max){return min+Math.floor(Math.random()*(max-min+1))}
