import{SKILLS,TICK_MS}from'./data.js';
import{getItem,ITEM_TYPES,EQUIPMENT_SLOTS,createUpgrade,stackKey}from'./items.js';
import{ENEMIES,COMBAT_STYLES,styledAttack,styledStrength,styledDefense,weaknessAttack,weaknessDamage,reduceIncoming,rollHit,maxHit,randomQuantity}from'./combat.js';

const SAVE_KEY='elderwild-web-save-v2';
const LEGACY_SAVE_KEY='elderwild-web-save-v1';
export const STARTING_SLOTS=28;
export function xpForLevel(level){if(level<=1)return 0;let total=0;for(let l=2;l<=Math.min(level,99);l++)total+=Math.floor((l-1)+300*Math.pow(2,(l-1)/7));return Math.floor(total/4)}
export function levelForXp(xp){let level=1;for(let l=2;l<=99;l++){if(xp>=xpForLevel(l))level=l;else break}return level}
function baseCombat(){return{active:false,enemyName:null,enemyHP:0,playerHP:1,style:COMBAT_STYLES.ATTACK,playerTick:0,enemyTick:0,autoEatCooldown:0,lastLog:'Choose an enemy to fight.'}}
function freshState(){return{version:2,playerName:'Adventurer',autoEatThreshold:50,equippedFoodName:null,skills:Object.fromEntries(SKILLS.map(s=>[s.name,{xp:0,actions:0}])),inventory:[],slotCapacity:STARTING_SLOTS,equipment:{},activity:null,combat:baseCombat(),lastSavedAt:Date.now()}}
function normalizeEntry(raw){if(!raw)return null;if(typeof raw==='string')return{...getItem(raw),quantity:1};const base=getItem(raw.name?.replace(/ \+\d+$/,''));return{...base,...raw,quantity:Math.max(0,raw.quantity||0)}}
function normalizeEquipment(raw={}){return Object.fromEntries(Object.entries(raw).filter(([,v])=>v).map(([slot,v])=>[slot,normalizeEntry({...v,quantity:1})]))}
function migrateLegacy(saved){const base=freshState();const inventory=Object.entries(saved.inventory||{}).filter(([,q])=>q>0).map(([name,quantity])=>({...getItem(name),quantity}));return{...base,...saved,version:2,skills:{...base.skills,...saved.skills},inventory,slotCapacity:STARTING_SLOTS,equipment:{},activity:null,combat:base.combat}}
export class Game{
  constructor(onChange=()=>{}){this.onChange=onChange;this.state=this.load();this.timer=null;if(this.state.combat.active)this.startLoop()}
  load(){try{let raw=localStorage.getItem(SAVE_KEY);if(!raw){const legacy=localStorage.getItem(LEGACY_SAVE_KEY);if(!legacy)return freshState();const migrated=migrateLegacy(JSON.parse(legacy));localStorage.setItem(SAVE_KEY,JSON.stringify(migrated));return migrated}const saved=JSON.parse(raw),base=freshState();const loaded={...base,...saved,autoEatThreshold:Math.max(10,Math.min(90,Number(saved.autoEatThreshold)||50)),skills:{...base.skills,...saved.skills},inventory:Array.isArray(saved.inventory)?saved.inventory.map(normalizeEntry).filter(Boolean):[],slotCapacity:Math.max(STARTING_SLOTS,saved.slotCapacity||STARTING_SLOTS),equipment:normalizeEquipment(saved.equipment),combat:{...base.combat,...saved.combat},activity:null};if(loaded.equippedFoodName&&!loaded.inventory.some(i=>i.name===loaded.equippedFoodName&&i.quantity>0))loaded.equippedFoodName=null;return loaded}catch{return freshState()}}
  save(){this.state.lastSavedAt=Date.now();localStorage.setItem(SAVE_KEY,JSON.stringify(this.state))}
  reset(){localStorage.removeItem(SAVE_KEY);localStorage.removeItem(LEGACY_SAVE_KEY);if(this.timer){clearInterval(this.timer);this.timer=null}this.state=freshState();this.save();this.onChange()}
  setName(name){this.state.playerName=(name||'Adventurer').trim().slice(0,24)||'Adventurer';this.save();this.onChange()}
  setAutoEatThreshold(value){this.state.autoEatThreshold=Math.max(10,Math.min(90,Math.round(Number(value)||50)));this.save();this.onChange()}
  getSkill(name){const data=SKILLS.find(s=>s.name===name),state=this.state.skills[name]||{xp:0,actions:0};return{...data,...state,level:levelForXp(state.xp)}}
  totalLevel(){return SKILLS.reduce((sum,s)=>sum+this.getSkill(s.name).level,0)}
  usedSlots(){return this.state.inventory.filter(e=>e.quantity>0&&e.type!==ITEM_TYPES.CURRENCY&&e.type!==ITEM_TYPES.PET).length}
  findStack(item){const key=stackKey(item);return this.state.inventory.find(e=>stackKey(e)===key)}
  canAddItem(item){return item.type===ITEM_TYPES.CURRENCY||item.type===ITEM_TYPES.PET||!!this.findStack(item)||this.usedSlots()<this.state.slotCapacity}
  addItem(nameOrItem,quantity=1){const item=typeof nameOrItem==='string'?getItem(nameOrItem):nameOrItem;if(quantity<=0||!this.canAddItem(item))return false;const existing=this.findStack(item);if(existing)existing.quantity+=quantity;else this.state.inventory.push({...item,quantity});this.save();return true}
  removeItem(item,quantity=1){const existing=this.findStack(item);if(!existing||quantity<=0||existing.quantity<quantity)return false;existing.quantity-=quantity;if(existing.quantity<=0)this.state.inventory=this.state.inventory.filter(e=>e!==existing);this.save();return true}
  combineEquipment(item){const existing=this.findStack(item);if(!existing||existing.type!==ITEM_TYPES.EQUIPMENT||existing.quantity<2||(existing.upgradeLevel||0)>=10)return false;const upgraded=createUpgrade(existing),sourceWillRemain=existing.quantity>2,target=this.findStack(upgraded);if(!target&&sourceWillRemain&&this.usedSlots()>=this.state.slotCapacity)return false;existing.quantity-=2;if(existing.quantity<=0)this.state.inventory=this.state.inventory.filter(e=>e!==existing);if(target)target.quantity++;else this.state.inventory.push({...upgraded,quantity:1});this.save();this.onChange();return true}
  getEquipped(slot){return this.state.equipment[slot]||null}
  equippedItems(){return Object.values(this.state.equipment).filter(Boolean)}
  equipmentBonus(stat){return this.equippedItems().reduce((sum,item)=>sum+(Number(item[stat])||0),0)}
  effectiveAttack(){return this.getSkill('Attack').level+this.equipmentBonus('attack')}
  effectiveStrength(){return this.getSkill('Strength').level+this.equipmentBonus('strength')}
  effectiveDefense(){return this.getSkill('Defense').level+this.equipmentBonus('defense')}
  maxHP(){return Math.max(1,this.getSkill('HP').level+this.equipmentBonus('hp'))}
  attackSpeed(){return Math.max(1,this.getEquipped(EQUIPMENT_SLOTS.WEAPON)?.attackSpeed||4)}
  meetsEquipmentRequirement(item){return item.slot===EQUIPMENT_SLOTS.WEAPON?this.getSkill('Attack').level>=(item.requiredAttack||0):this.getSkill('Defense').level>=(item.requiredDefense||0)}
  equipItem(item){const source=this.findStack(item);if(!source||source.type!==ITEM_TYPES.EQUIPMENT||source.slot===EQUIPMENT_SLOTS.NONE||!this.meetsEquipmentRequirement(source))return false;const slot=source.slot,previous=this.getEquipped(slot),snapshot={...source};if(!this.removeItem(source,1))return false;if(previous&&!this.canAddItem(previous)){this.addItem(snapshot,1);return false}this.state.equipment[slot]={...snapshot,quantity:1};if(previous)this.addItem(previous,1);this.state.combat.playerHP=Math.min(this.state.combat.playerHP,this.maxHP());this.save();this.onChange();return true}
  unequipItem(slot){const item=this.getEquipped(slot);if(!item||!this.canAddItem(item))return false;delete this.state.equipment[slot];this.addItem(item,1);this.state.combat.playerHP=Math.min(this.state.combat.playerHP,this.maxHP());this.save();this.onChange();return true}
  selectedFood(){return this.state.equippedFoodName?this.state.inventory.find(i=>i.name===this.state.equippedFoodName&&i.type===ITEM_TYPES.FOOD&&i.quantity>0)||null:null}
  selectFood(item){const food=this.findStack(item);if(!food||food.type!==ITEM_TYPES.FOOD||food.healing<=0)return false;this.state.equippedFoodName=food.name;this.save();this.onChange();return true}
  clearFood(){this.state.equippedFoodName=null;this.save();this.onChange()}
  shouldAutoEat(){const c=this.state.combat;if(!c.active||c.playerHP<=0||c.playerHP>=this.maxHP())return false;return c.playerHP<=Math.ceil(this.maxHP()*this.state.autoEatThreshold/100)}
  tryAutoEat(){const c=this.state.combat;if(c.autoEatCooldown>0||!this.shouldAutoEat())return false;const food=this.selectedFood();if(!food)return false;const name=food.name,heal=food.healing;if(!this.removeItem(food,1))return false;c.playerHP=Math.min(this.maxHP(),c.playerHP+heal);c.autoEatCooldown=4;if(!this.state.inventory.some(i=>i.name===name&&i.quantity>0))this.state.equippedFoodName=null;c.lastLog=`You eat ${name} and heal ${heal} HP.`;return true}
  startActivity(skillName,activityName){const skill=this.getSkill(skillName),activity=skill.activities.find(a=>a.name===activityName);if(!activity||skill.level<activity.level)return false;if(activity.item&&!this.canAddItem(getItem(activity.item)))return false;this.stopFight(false);this.state.activity={skillName,activityName,tick:0,totalTicks:activity.ticks};this.startLoop();this.save();this.onChange();return true}
  stopActivity(notify=true){this.state.activity=null;this.maybeStopLoop();this.save();if(notify)this.onChange()}
  startFight(enemyName){const enemy=ENEMIES.find(e=>e.name===enemyName);if(!enemy)return false;if(enemy.requirement&&this.getSkill(enemy.requirement.skill).level<enemy.requirement.level)return false;this.stopActivity(false);this.state.combat={active:true,enemyName:enemy.name,enemyHP:enemy.hp,playerHP:this.maxHP(),style:this.state.combat.style||COMBAT_STYLES.ATTACK,playerTick:0,enemyTick:0,autoEatCooldown:0,lastLog:`You engage ${enemy.name}.`};this.startLoop();this.save();this.onChange();return true}
  stopFight(notify=true){this.state.combat={...this.state.combat,active:false,enemyName:null,enemyHP:0,playerTick:0,enemyTick:0,autoEatCooldown:0};this.maybeStopLoop();this.save();if(notify)this.onChange()}
  setCombatStyle(style){if(!Object.values(COMBAT_STYLES).includes(style))return;this.state.combat.style=style;this.save();this.onChange()}
  startLoop(){if(this.timer)return;this.timer=setInterval(()=>this.tick(),TICK_MS)}
  maybeStopLoop(){if(!this.state.activity&&!this.state.combat.active&&this.timer){clearInterval(this.timer);this.timer=null}}
  tick(){if(this.state.activity)this.tickActivity();if(this.state.combat.active)this.tickCombat();this.onChange()}
  tickActivity(){const active=this.state.activity,skillDef=SKILLS.find(s=>s.name===active.skillName),activity=skillDef?.activities.find(a=>a.name===active.activityName);if(!activity){this.stopActivity(false);return}active.tick++;if(active.tick>=active.totalTicks){if(activity.item&&!this.canAddItem(getItem(activity.item))){this.stopActivity(false);return}active.tick=0;const skillState=this.state.skills[active.skillName];skillState.xp+=activity.xp;skillState.actions=(skillState.actions||0)+1;if(activity.item)this.addItem(activity.item,1);this.save()}}
  tickCombat(){const c=this.state.combat,enemy=ENEMIES.find(e=>e.name===c.enemyName);if(!enemy){this.stopFight(false);return}if(c.autoEatCooldown>0)c.autoEatCooldown--;this.tryAutoEat();c.playerTick++;c.enemyTick++;const style=c.style,atk=weaknessAttack(enemy,style,styledAttack(this.effectiveAttack(),style)),str=styledStrength(this.effectiveStrength(),style),def=styledDefense(this.effectiveDefense(),style);if(c.playerTick>=this.attackSpeed()){c.playerTick=0;let damage=rollHit(atk,enemy.defense,maxHit(str));if(damage>0)damage=weaknessDamage(enemy,style,damage);c.enemyHP=Math.max(0,c.enemyHP-damage);c.lastLog=damage?`You hit ${enemy.name} for ${damage}.`:`You miss ${enemy.name}.`;if(damage>0){this.state.skills[style].xp+=damage*4;this.state.skills.HP.xp+=damage}if(c.enemyHP<=0){this.resolveVictory(enemy);return}}
    if(c.enemyTick>=enemy.attackSpeed){c.enemyTick=0;let damage=rollHit(enemy.attack,def,maxHit(enemy.strength));damage=reduceIncoming(style,damage);c.playerHP=Math.max(0,c.playerHP-damage);c.lastLog=damage?`${enemy.name} hits you for ${damage}.`:`${enemy.name} misses you.`;if(c.playerHP<=0){c.lastLog=`You were defeated by ${enemy.name}.`;c.active=false;c.enemyName=null;this.maybeStopLoop();this.save();return}this.tryAutoEat()}this.save()}
  resolveVictory(enemy){const drops=[];for(const drop of enemy.drops){if(Math.random()<=drop.chance){const quantity=randomQuantity(drop.min,drop.max);if(this.addItem(drop.item,quantity))drops.push(`${quantity}× ${drop.item}`)}}this.state.combat.lastLog=`Defeated ${enemy.name}${drops.length?` — ${drops.join(', ')}`:' — no drops'}.`;this.state.combat.active=false;this.state.combat.enemyName=null;this.state.combat.enemyHP=0;this.maybeStopLoop();this.save()}
}
