import{Game}from'./game.js';
import{ITEM_TYPES,EQUIPMENT_SLOTS,createUpgrade,stackKey,getItem}from'./items.js';

function isSlotItem(i){return i&&i.quantity>0&&i.type!==ITEM_TYPES.CURRENCY&&i.type!==ITEM_TYPES.PET}
function sameStack(a,b){return !!a&&!!b&&stackKey(a)===stackKey(b)}
function addResult(list,item,quantity){if(quantity<=0)return;const found=list.find(e=>sameStack(e.item,item));if(found)found.quantity+=quantity;else list.push({item:{...item},quantity})}

if(!Game.prototype.__inventoryParityPatched){
  Game.prototype.nextSlotCost=function(){const purchased=Math.max(0,(this.state.slotCapacity||28)-28);return Math.min(Number.MAX_SAFE_INTEGER,Math.ceil(100*Math.pow(1.5,purchased)))};
  Game.prototype.purchaseNextSlot=function(){const cost=this.nextSlotCost(),coins=this.findStack(getItem('Coins'));if(!coins||coins.quantity<cost)return false;if(!this.removeItem(coins,cost))return false;this.state.slotCapacity=(this.state.slotCapacity||28)+1;this.save();this.onChange();return true};
  Game.prototype.canReplaceItem=function(itemToRemove,itemToAdd){const source=this.findStack(itemToRemove);if(!source)return false;if(itemToAdd?.type===ITEM_TYPES.PET||itemToAdd?.type===ITEM_TYPES.CURRENCY||sameStack(itemToRemove,itemToAdd))return true;const other=this.state.inventory.find(e=>e!==source&&e.quantity>0&&sameStack(e,itemToAdd));if(other)return true;const usedAfter=this.usedSlots()-(source.quantity===1&&isSlotItem(source)?1:0);return usedAfter<this.state.slotCapacity};
  Game.prototype.equipItem=function(item){const source=this.findStack(item);if(!source||source.type!==ITEM_TYPES.EQUIPMENT||source.slot===EQUIPMENT_SLOTS.NONE||!this.meetsEquipmentRequirement(source))return false;const slot=source.slot,previous=this.getEquipped(slot),snapshot={...source,quantity:1};if(previous&&!this.canReplaceItem(source,previous))return false;if(!this.removeItem(source,1))return false;this.state.equipment[slot]=snapshot;if(previous&&!this.addItem(previous,1)){this.state.equipment[slot]=previous;this.addItem(snapshot,1);return false}this.state.combat.playerHP=Math.min(this.state.combat.playerHP,this.maxHP());this.save();this.onChange();return true};
  Game.prototype.combineAllEquipmentStack=function(item){const source=this.findStack(item);if(!source||source.type!==ITEM_TYPES.EQUIPMENT||(source.upgradeLevel||0)>=10||source.quantity<2)return{combinedPairs:0};const originalQty=source.quantity,final=[],created=[];let current={...source,quantity:1},count=originalQty;while(count>0){if((current.upgradeLevel||0)>=10){addResult(final,current,count);if((current.upgradeLevel||0)>(source.upgradeLevel||0))addResult(created,current,count);break}const rem=count%2;if(rem){addResult(final,current,rem);if((current.upgradeLevel||0)>(source.upgradeLevel||0))addResult(created,current,rem)}count=Math.floor(count/2);if(!count)break;current=createUpgrade(current)}const sourceRetained=final.find(e=>sameStack(e.item,source))?.quantity||0;const existingWithoutSource=this.state.inventory.filter(e=>e!==source&&e.quantity>0);let used=existingWithoutSource.filter(isSlotItem).length+(sourceRetained>0&&isSlotItem(source)?1:0);for(const r of final){if(sameStack(r.item,source))continue;const exists=existingWithoutSource.some(e=>sameStack(e,r.item));if(!exists&&isSlotItem(r.item))used++}if(used>this.state.slotCapacity)return{combinedPairs:0};this.state.inventory=this.state.inventory.filter(e=>e!==source);for(const r of final){const existing=this.state.inventory.find(e=>sameStack(e,r.item));if(existing)existing.quantity+=r.quantity;else this.state.inventory.push({...r.item,quantity:r.quantity})}const combinedPairs=originalQty-final.reduce((s,r)=>s+r.quantity,0);this.save();return{combinedPairs,created}};
  Game.prototype.combineAllEquipment=function(){let total=0,guard=0;while(guard++<500){const stack=this.state.inventory.find(e=>e.quantity>=2&&e.type===ITEM_TYPES.EQUIPMENT&&(e.upgradeLevel||0)<10);if(!stack)break;const r=this.combineAllEquipmentStack(stack);if(!r.combinedPairs)break;total+=r.combinedPairs}if(total>0){this.save();this.onChange()}return total};
  Game.prototype.sellInventoryCategory=function(category){const match=i=>category==='equipment'?i.type===ITEM_TYPES.EQUIPMENT:category==='food'?i.type===ITEM_TYPES.FOOD:category==='junk'?!!i.isJunk:false;const selling=this.state.inventory.filter(i=>i.quantity>0&&match(i));if(!selling.length)return{quantity:0,gold:0};let quantity=0,gold=0;const selected=this.state.equippedFoodName;for(const i of selling){quantity+=i.quantity;gold+=Math.max(0,Number(i.value)||0)*i.quantity}this.state.inventory=this.state.inventory.filter(i=>!match(i));if(selected&&!this.state.inventory.some(i=>i.name===selected&&i.quantity>0))this.state.equippedFoodName=null;if(gold>0){const coins=this.state.inventory.find(i=>i.name==='Coins'&&i.type===ITEM_TYPES.CURRENCY);if(coins)coins.quantity+=gold;else this.state.inventory.push({...getItem('Coins'),quantity:gold})}this.save();this.onChange();return{quantity,gold}};
  Game.prototype.__inventoryParityPatched=true;
}
