import A from'./items-data-1.js';import B from'./items-data-2.js';import C from'./items-data-3.js';import D from'./items-data-4.js';import E from'./items-data-5.js';
export const ITEM_TYPES={MATERIAL:'Material',FOOD:'Food',CURRENCY:'Currency',EQUIPMENT:'Equipment',PET:'Pet'};
export const EQUIPMENT_SLOTS={NONE:'None',HEAD:'Head',BODY:'Body',LEGS:'Legs',WEAPON:'Weapon',SHIELD:'Shield',GLOVES:'Gloves',BOOTS:'Boots',AMULET:'Amulet',RING:'Ring',FOOD:'Food'};
function clampLevel(v){return Math.max(1,Math.min(99,Math.ceil(v)))}
function descriptionFor(i){if(i.type===ITEM_TYPES.FOOD)return`${i.name} restores ${i.healing} HP when eaten.`;if(i.type===ITEM_TYPES.PET)return`${i.name} is a treasured companion rather than a normal inventory item.`;if(i.type===ITEM_TYPES.CURRENCY)return`${i.name} is accepted currency throughout ScapeRunner.`;if(i.type===ITEM_TYPES.EQUIPMENT)return`${i.name} is ${i.slot.toLowerCase()} equipment with combat bonuses.`;return`${i.name} is a trade or crafting material worth ${i.value.toLocaleString()} coin${i.value===1?'':'s'}.`}
function item(name,{icon='•',type=ITEM_TYPES.MATERIAL,slot=EQUIPMENT_SLOTS.NONE,value=0,attack=0,strength=0,defense=0,hp=0,healing=0,attackSpeed=4,upgradeLevel=0}={}){let requiredAttack=0,requiredDefense=0;if(type===ITEM_TYPES.EQUIPMENT&&slot!==EQUIPMENT_SLOTS.NONE){if(slot===EQUIPMENT_SLOTS.WEAPON){const power=attack+strength+Math.trunc(defense/2);requiredAttack=clampLevel(power*.75)}else{const power=defense+hp*3+Math.trunc((attack+strength)/2);requiredDefense=clampLevel(power*.9)}}const result={name,icon,description:'',type,slot,value,attack,strength,defense,hp,requiredAttack,requiredDefense,healing,attackSpeed,upgradeLevel,isJunk:type===ITEM_TYPES.MATERIAL};result.description=descriptionFor(result);return result}
const ROWS=[...A,...B,...C,...D,...E];
export const ITEMS=Object.fromEntries(ROWS.map(([name,icon,type,slot,value,attack,strength,defense,hp,healing,attackSpeed])=>[name,item(name,{icon,type,slot,value,attack,strength,defense,hp,healing,attackSpeed})]));
export const ITEM_COUNT=ROWS.length;
export function getItem(name){return ITEMS[name]||item(name)}
export function stackKey(entry){return`${entry.name}::${entry.upgradeLevel||0}`}
export function createUpgrade(source){if(source.type!==ITEM_TYPES.EQUIPMENT||(source.upgradeLevel||0)>=10)return source;const level=(source.upgradeLevel||0)+1,baseName=source.name.replace(/ \+\d+$/,''),bonus=v=>v===0?0:Math.ceil(v*1.02);return{...source,name:`${baseName} +${level}`,upgradeLevel:level,attack:bonus(source.attack||0),strength:bonus(source.strength||0),defense:bonus(source.defense||0),hp:bonus(source.hp||0)}}
