import{ENEMIES}from'./combat.js';
const g=window.__elderwildGame;
if(g&&!document.querySelector('.landing-overlay')){
const style=document.createElement('style');style.textContent=`body.landing-open{overflow:hidden}.landing-overlay{position:fixed;inset:0;z-index:100;background:linear-gradient(#07100bb8,#07100be8),url('assets/backgrounds/background_landing.png') center/cover no-repeat;display:flex;align-items:center;justify-content:center;padding:18px;overflow:auto}.landing-card{width:min(360px,100%);display:grid;gap:12px;text-align:center}.landing-title{font-size:42px;line-height:1;font-weight:900;letter-spacing:.04em;color:#72d88d;text-shadow:0 3px 8px #000}.landing-tag{color:#dce7df;font-size:14px}.landing-save{padding:14px;border:1px solid #4f735d;border-radius:12px;background:linear-gradient(#202823ed,#101512f2);box-shadow:0 14px 36px #000b;text-align:left}.landing-name{text-align:center;color:#8ce7a6;font-size:21px;font-weight:900;margin-bottom:10px}.landing-rule{height:1px;background:#4f735d;margin:6px 0 8px}.landing-stat{display:grid;grid-template-columns:1fr auto;gap:12px;padding:5px 0;color:#d9e4dc;font-size:13px}.landing-stat strong{color:#f1f6f2}.landing-offline strong{color:#8ce7a6}.landing-enter{width:100%;padding:12px;border:1px solid #65cc82;border-radius:9px;background:#214b31;color:#eef8f1;font-size:15px;font-weight:900}.landing-hint{text-align:center;color:#93a198;font-size:10px;margin-top:4px}.landing-firefly{position:absolute;width:3px;height:3px;border-radius:50%;background:#8cf6a5;box-shadow:0 0 8px #8cf6a5;opacity:.15;animation:landingFly 4s ease-in-out infinite alternate;pointer-events:none}@keyframes landingFly{to{opacity:.85;transform:translate(7px,-13px) scale(1.6)}}`;
document.head.append(style);document.body.classList.add('landing-open');
const activity=g.state.activity?.skillName?`${g.state.activity.skillName}: ${g.state.activity.activityName}`:g.state.combat?.active?`Fighting ${g.state.combat.enemyName}`:g.state.combat?.respawning?`Waiting for ${g.state.combat.respawnEnemyName}`:'Idle';
const offline=window.__elderwildOfflineDuration||'0s',skillCount=Object.keys(g.state.skills||{}).length;
const overlay=document.createElement('div');overlay.className='landing-overlay';overlay.innerHTML=`<section class="landing-card"><div><div class="landing-title">SCAPERUNNER</div><div class="landing-tag">Your idle adventure awaits</div></div><div class="landing-save" role="button" tabindex="0"><div class="landing-name">${String(g.state.playerName||'Adventurer').toUpperCase()}</div><div class="landing-rule"></div><div class="landing-stat"><span>Skill Total</span><strong>${g.totalLevel()} / ${skillCount*99}</strong></div><div class="landing-stat"><span>Total Kills</span><strong>${g.totalKills().toLocaleString()}</strong></div><div class="landing-stat"><span>Collection Log</span><strong>${g.completedCollections()} / ${ENEMIES.length}</strong></div><div class="landing-stat"><span>Activity</span><strong>${activity}</strong></div><div class="landing-stat landing-offline"><span>Offline Progress</span><strong>${offline}</strong></div><button class="landing-enter" type="button">Continue Adventure</button><div class="landing-hint">Tap your character to play</div></div></section>`;
for(let i=0;i<14;i++){const f=document.createElement('span');f.className='landing-firefly';f.style.left=`${6+Math.random()*88}%`;f.style.top=`${7+Math.random()*84}%`;f.style.animationDelay=`-${Math.random()*4}s`;f.style.animationDuration=`${3+Math.random()*4}s`;overlay.append(f)}
const enter=()=>{overlay.remove();document.body.classList.remove('landing-open')};overlay.querySelector('.landing-save').addEventListener('click',enter);overlay.querySelector('.landing-save').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();enter()}});document.body.append(overlay);
}
