const style=document.createElement('style');
style.textContent=`.xp-bonus-badge{display:inline-block;margin-left:6px;padding:2px 6px;border:1px solid #4f735d;border-radius:99px;color:#72d88d;background:#172019;font-size:11px;font-weight:700}.xp-bonus-note{margin-top:5px;color:#72d88d;font-size:12px}.combat-xp-bonus{margin-top:5px;color:#72d88d;font-size:12px}`;
document.head.appendChild(style);

function getGame(){return window.__elderwildGame}
function enhanceSkill(){const game=getGame();if(!game)return;const heading=document.querySelector('#view .panel h2');if(!heading)return;const match=heading.textContent.match(/^(.*?) — Level /);if(!match)return;const skillName=match[1].replace(/^\S+\s+/,'').trim(),skill=game.getSkill(skillName);if(!skill?.activities)return;const pct=game.skillXpBonusPercent?.(skillName)||0;let note=document.querySelector('#view .xp-bonus-note');if(!note){note=document.createElement('div');note.className='xp-bonus-note';heading.insertAdjacentElement('afterend',note)}note.textContent=pct?`Progression bonus: +${pct}% XP`:'Progression bonus unlocks at level 10';for(const row of document.querySelectorAll('#view .activity-card')){const muted=row.querySelector('.muted');if(!muted||muted.dataset.xpBonus==='1')continue;const m=muted.textContent.match(/ · ([\d.]+) XP · /);if(!m)continue;const base=Number(m[1]);if(!Number.isFinite(base))continue;const boosted=base*(1+pct/100);muted.innerHTML=muted.innerHTML.replace(` · ${m[1]} XP · `,` · ${boosted.toLocaleString(undefined,{maximumFractionDigits:1})} XP${pct?` <span class="xp-bonus-badge">+${pct}%</span>`:''} · `);muted.dataset.xpBonus='1'}}
function enhanceCombat(){const game=getGame();if(!game)return;const c=game.state.combat;if(!c?.active)return;const enemy=window.__elderwildEnemies?.find?.(e=>e.name===c.enemyName);if(!enemy)return;const panel=document.querySelector('#view .panel');if(!panel)return;let note=panel.querySelector('.combat-xp-bonus');if(!note){note=document.createElement('div');note.className='combat-xp-bonus';const summary=panel.querySelector('.card');summary?.insertAdjacentElement('afterend',note)}const pct=game.combatXpBonusPercent?.(enemy)||0;if(note)note.textContent=pct?`Combat progression bonus: +${pct}% XP against ${enemy.name}`:`Combat progression bonus: none against ${enemy.name}`}
let queued=false;function enhance(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;enhanceSkill();enhanceCombat()})}
new MutationObserver(enhance).observe(document.querySelector('#view'),{childList:true,subtree:true});
window.addEventListener('elderwild-game-state',enhance);enhance();
