const style=document.createElement('style');
style.textContent=`.offline-layer{position:fixed;inset:0;z-index:45;display:grid;place-items:center;padding:18px;background:#000b}.offline-card{width:min(430px,calc(100vw - 36px));max-height:min(78vh,620px);overflow:auto;padding:20px;border:2px solid #57c879;border-radius:14px;background:linear-gradient(#252c29,#151917);box-shadow:0 14px 48px #000d}.offline-card h2{margin:0 0 4px;color:#72d88d;text-align:center}.offline-card .away-time{text-align:center;color:#a7b5ab;margin-bottom:14px}.offline-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin:10px 0}.offline-stat{padding:10px;border:1px solid #35493d;border-radius:8px;background:#121714;text-align:center}.offline-stat strong{display:block;color:#72d88d;font-size:18px}.offline-loot{display:grid;gap:5px;margin:10px 0}.offline-loot-row{display:flex;justify-content:space-between;gap:12px;padding:7px 9px;border:1px solid #2e4135;border-radius:6px;background:#111513}.offline-new{color:#ffe26a}.offline-warning{padding:9px;border:1px solid #754141;border-radius:7px;background:#351d1d;color:#ffb0b0}.offline-continue{width:100%;margin-top:14px;padding:11px;border:1px solid #65cc82;border-radius:8px;background:#27332c;color:#edf4ef;font-weight:700}@media(max-width:420px){.offline-grid{grid-template-columns:1fr}}`;
document.head.appendChild(style);

function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function n(v,d=0){return Number(v||0).toLocaleString(undefined,{maximumFractionDigits:d})}
function show(){const summary=window.__elderwildOfflineSummary,game=window.__elderwildGame;if(game?.state?.activity&&!game.timer)game.startLoop();if(!summary)return;const layer=document.createElement('div');layer.className='offline-layer';const card=document.createElement('section');card.className='offline-card';const duration=window.__elderwildOfflineDuration||'some time';if(summary.kind==='skilling')card.innerHTML=skilling(summary,duration);else card.innerHTML=combat(summary,duration);layer.appendChild(card);document.body.appendChild(layer);card.querySelector('.offline-continue')?.addEventListener('click',()=>{layer.remove();window.__elderwildOfflineSummary=null;game?.save?.();game?.onChange?.()})}
function skilling(s,duration){const warning=s.inventoryFull?'<p class="offline-warning">Training paused because your inventory was full.</p>':'';const level=s.endLevel&&s.startLevel&&s.endLevel>s.startLevel?`<p class="offline-new">Level up! ${esc(s.skill)} ${s.startLevel} → ${s.endLevel}</p>`:'';const reward=s.item&&s.quantity?`<div class="offline-loot-row"><span>${esc(s.item)}</span><strong>× ${n(s.quantity)}</strong></div>`:'';return`<h2>Offline Progress</h2><div class="away-time">Away for ${esc(duration)}</div><h3>${esc(s.skill)} · ${esc(s.activity)}</h3><div class="offline-grid"><div class="offline-stat"><strong>${n(s.actions)}</strong><small>Actions completed</small></div><div class="offline-stat"><strong>${n(s.xp,1)}</strong><small>XP gained</small></div></div>${level}${reward?`<h3>Rewards</h3><div class="offline-loot">${reward}</div>`:''}${warning}<p class="muted">${s.resumed?'Your activity has resumed automatically.':'Your activity is currently stopped.'}</p><button class="offline-continue">Continue</button>`}
function combat(s,duration){const loot=Object.entries(s.loot||{}).sort((a,b)=>b[1]-a[1]).map(([item,qty])=>`<div class="offline-loot-row ${s.newItems?.includes(item)?'offline-new':''}"><span>${s.newItems?.includes(item)?'*NEW* ':''}${esc(item)}</span><strong>× ${n(qty)}</strong></div>`).join('');let warning='';if(s.died)warning=`<p class="offline-warning">You were defeated by ${esc(s.enemy)}. Auto-fight has stopped.</p>`;else if(s.inventoryFull)warning='<p class="offline-warning">Combat stopped because your inventory became full.</p>';return`<h2>Offline Combat</h2><div class="away-time">Away for ${esc(duration)}</div><h3>${esc(s.enemy)}</h3><div class="offline-grid"><div class="offline-stat"><strong>${n(s.kills)}</strong><small>Kills</small></div><div class="offline-stat"><strong>${n(s.processed)}</strong><small>Ticks simulated</small></div><div class="offline-stat"><strong>${n(s.hpXp,1)}</strong><small>HP XP</small></div><div class="offline-stat"><strong>${n(s.styleXp,1)}</strong><small>Style XP</small></div></div>${loot?`<h3>Loot</h3><div class="offline-loot">${loot}</div>`:'<p class="muted">No loot received.</p>'}${warning}<p class="muted">${s.resumed?'Auto-fight has resumed from the saved state.':'The saved combat session has ended.'}</p><button class="offline-continue">Continue</button>`}
queueMicrotask(show);
