import{Game,levelForXp,xpForLevel}from'./game.js';
import{SKILLS,TICK_MS}from'./data.js';
import{getItem}from'./items.js';
import{ENEMIES,COMBAT_STYLES,styledAttack,styledStrength,styledDefense,weaknessAttack,weaknessDamage,reduceIncoming,reduceEnemyIncoming,enemyAttackLevel,enemyDefenseLevel,enemyAttackSpeed,enemyRegenAmount,rollHit,maxHit,randomQuantity}from'./combat.js';

const SAVE_KEY='elderwild-web-save-v2',RESPAWN_TICKS=12;
function fmtTicks(ticks){const seconds=Math.max(0,ticks)*TICK_MS/1000;if(seconds<60)return`${seconds.toFixed(seconds<10?1:0)}s`;if(seconds<3600)return`${Math.floor(seconds/60)}m ${Math.floor(seconds%60)}s`;return`${Math.floor(seconds/3600)}h ${Math.floor((seconds%3600)/60)}m`}
function rawSave(){try{return JSON.parse(localStorage.getItem(SAVE_KEY)||'null')}catch{return null}}
function addLoot(map,item,qty){map[item]=(map[item]||0)+qty}
function activityDef(skillName,activityName){const s=SKILLS.find(x=>x.name===skillName),a=s?.activities?.find(x=>x.name===activityName);return{s,a}}
function calcSkillXp(startXp,baseXp,count){let total=0,current=Number(startXp)||0,remaining=Math.max(0,Math.floor(count));while(remaining>0){const level=levelForXp(current),mult=1+Math.min(10,Math.floor(Math.max(1,level)/10))/100,per=baseXp*mult;if(level>=99){total+=remaining*per;break}const toNext=Math.max(0,xpForLevel(level+1)-current),actions=Math.max(1,Math.ceil(toNext/per)),take=Math.min(remaining,actions);total+=take*per;current+=take*per;remaining-=take}return total}
function processSkilling(game,state,raw,elapsedTicks){const saved=raw.activity;if(!saved?.skillName||!saved?.activityName)return null;const{a}=activityDef(saved.skillName,saved.activityName);if(!a)return null;const totalTicks=Math.max(1,Number(saved.totalTicks)||Number(a.ticks)||1),startingTick=Math.max(0,Number(saved.tick)||0),available=startingTick+elapsedTicks,actions=Math.floor(available/totalTicks),remainder=available%totalTicks;if(actions<=0){state.activity={...saved,tick:remainder,totalTicks};return{kind:'skilling',skill:saved.skillName,activity:saved.activityName,ticks:elapsedTicks,actions:0,xp:0,item:a.item||null,quantity:0,inventoryFull:false,resumed:true}}
const reward=a.item?getItem(a.item):null;if(reward&&!game.canAddItem(reward)){state.activity=null;return{kind:'skilling',skill:saved.skillName,activity:saved.activityName,ticks:elapsedTicks,actions:0,xp:0,item:a.item,quantity:0,inventoryFull:true,resumed:false}}
const skillState=state.skills[saved.skillName],startLevel=levelForXp(skillState.xp),xp=calcSkillXp(skillState.xp,a.xp,actions);skillState.xp+=xp;skillState.actions=(skillState.actions||0)+actions;if(reward)game.addItem(reward,Math.min(actions,Number.MAX_SAFE_INTEGER));const endLevel=levelForXp(skillState.xp);state.activity={...saved,tick:remainder,totalTicks};return{kind:'skilling',skill:saved.skillName,activity:saved.activityName,ticks:elapsedTicks,actions,xp,item:a.item||null,quantity:reward?actions:0,startLevel,endLevel,inventoryFull:false,resumed:true}}
function simulateCombat(game,state,elapsedTicks){const c=state.combat,enemyName=c.active?c.enemyName:(c.respawning?c.respawnEnemyName:null),enemy=ENEMIES.find(e=>e.name===enemyName);if(!enemy)return null;const summary={kind:'combat',enemy:enemy.name,ticks:elapsedTicks,processed:0,kills:0,hpXp:0,styleXp:0,loot:{},newItems:[],died:false,inventoryFull:false,resumed:false,auto:!!c.autoFightEnabled};let remaining=elapsedTicks;
function tryEat(){if(c.autoEatCooldown<=0)game.tryAutoEat()}
function finishKill(){for(const drop of enemy.drops){const chance=game.effectiveDropChance?.(drop.chance)??drop.chance;if(Math.random()>chance)continue;const qty=randomQuantity(drop.min,drop.max);if(!game.addItem(drop.item,qty)){summary.inventoryFull=true;continue}addLoot(summary.loot,drop.item,qty);game.recordLuckiestDrop?.(drop.item,game.getKillCount(enemy.name)+1,chance,`${enemy.name} kills`);const known=game.hasDiscoveredItem(drop.item);game.recordCollectionDrop(drop.item);if(!known)summary.newItems.push(drop.item)}game.recordCollectionKill(enemy.name);summary.kills++;if(summary.inventoryFull){c.active=false;c.respawning=false;c.autoFightEnabled=false;return false}if(c.autoFightEnabled&&c.playerHP>0){c.active=false;c.respawning=true;c.respawnEnemyName=enemy.name;c.respawnTicks=RESPAWN_TICKS;c.enemyName=null;c.enemyHP=0;c.playerTick=0;c.enemyTick=0;return true}c.active=false;c.enemyName=null;c.enemyHP=0;c.respawning=false;return false}
while(remaining>0&&!summary.died&&!summary.inventoryFull){if(c.respawning){const step=Math.min(remaining,Math.max(1,c.respawnTicks||RESPAWN_TICKS));remaining-=step;summary.processed+=step;c.respawnTicks=Math.max(0,(c.respawnTicks||RESPAWN_TICKS)-step);if(c.respawnTicks>0)continue;c.respawning=false;c.active=true;c.enemyName=enemy.name;c.enemyHP=enemy.hp;c.playerTick=0;c.enemyTick=0;continue}if(!c.active)break;const pSpeed=Math.max(1,game.attackSpeed()),eSpeed=Math.max(1,enemyAttackSpeed(enemy)),toP=Math.max(1,pSpeed-(c.playerTick||0)),toE=Math.max(1,eSpeed-(c.enemyTick||0)),toEat=c.autoEatCooldown>0?c.autoEatCooldown:(game.shouldAutoEat()?1:Number.MAX_SAFE_INTEGER),step=Math.max(1,Math.min(remaining,toP,toE,toEat));remaining-=step;summary.processed+=step;c.playerTick=(c.playerTick||0)+step;c.enemyTick=(c.enemyTick||0)+step;if(c.autoEatCooldown>0)c.autoEatCooldown=Math.max(0,c.autoEatCooldown-step);tryEat();
if(c.playerTick>=pSpeed){c.playerTick-=pSpeed;const style=c.style||COMBAT_STYLES.ATTACK,atk=weaknessAttack(enemy,style,styledAttack(game.effectiveAttack(),style)),str=styledStrength(game.effectiveStrength(),style);let damage=rollHit(atk,enemyDefenseLevel(enemy),maxHit(str));if(damage>0){damage=weaknessDamage(enemy,style,damage);damage=reduceEnemyIncoming(enemy,damage)}if(damage>0){const mult=game.combatXpMultiplier?.(enemy)||1,hp=damage*mult,sp=damage*4*mult;state.skills.HP.xp+=hp;state.skills[style].xp+=sp;summary.hpXp+=hp;summary.styleXp+=sp}c.enemyHP=Math.max(0,c.enemyHP-damage);if(c.enemyHP<=0){const continues=finishKill();if(!continues)break;continue}}
if(c.active&&c.enemyTick>=eSpeed){c.enemyTick-=eSpeed;const style=c.style||COMBAT_STYLES.ATTACK,def=styledDefense(game.effectiveDefense(),style),rawDamage=rollHit(enemyAttackLevel(enemy),def,maxHit(enemy.strength)),damage=reduceIncoming(style,rawDamage);c.playerHP=Math.max(0,c.playerHP-damage);if(rawDamage>0){const regen=enemyRegenAmount(enemy);if(regen>0)c.enemyHP=Math.min(enemy.hp,c.enemyHP+regen)}tryEat();if(c.playerHP<=0){summary.died=true;c.active=false;c.respawning=false;c.autoFightEnabled=false;c.enemyName=null;c.respawnEnemyName=null;break}}}
summary.resumed=!!(c.active||c.respawning);c.lastLog=summary.died?`Offline combat ended: you were defeated by ${enemy.name}.`:summary.inventoryFull?'Offline combat stopped because your inventory became full.':summary.resumed?`Offline combat processed ${summary.kills} kill${summary.kills===1?'':'s'} and resumed.`:`Offline combat processed ${summary.kills} kill${summary.kills===1?'':'s'}.`;return summary}

if(!Game.prototype.__pass4OfflinePatched){const originalLoad=Game.prototype.load;Game.prototype.load=function(...args){const raw=rawSave(),state=originalLoad.apply(this,args);if(!raw||!Number(raw.lastSavedAt))return state;const elapsed=Math.max(0,Math.floor((Date.now()-Number(raw.lastSavedAt))/TICK_MS));if(elapsed<=0)return state;this.state=state;const normalSave=this.save;this.save=()=>{};let summary=null;try{if(raw.activity?.skillName&&raw.activity?.activityName)summary=processSkilling(this,state,raw,elapsed);else if(raw.combat?.active||raw.combat?.respawning){state.combat={...state.combat,...raw.combat};summary=simulateCombat(this,state,elapsed)}}finally{this.save=normalSave}state.lastSavedAt=Date.now();window.__elderwildOfflineSummary=summary;if(summary)window.__elderwildOfflineDuration=fmtTicks(elapsed);try{localStorage.setItem(SAVE_KEY,JSON.stringify(state))}catch{}return state};Game.prototype.__pass4OfflinePatched=true}
