import{ENEMIES}from'./combat.js';

const style=document.createElement('style');
style.textContent=`.loot-meta-panel{margin-top:12px}.loot-meta-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.loot-meta-card{padding:10px;text-align:center;background:#151a17;border:1px solid #35493d;border-radius:8px}.loot-meta-card strong{display:block;color:#72d88d;font-size:18px}.loot-meta-card small{display:block;color:#a7b5ab;margin-top:3px}.luckiest-drop{margin-top:8px;padding:10px;background:#121714;border:1px solid #4f735d;border-radius:8px}.luckiest-drop strong{color:#72d88d}.pass2-boost-banner{margin:10px 0;padding:10px;border:1px solid #4f735d;border-radius:8px;background:#172019;text-align:center}.rare-notification-layer{position:fixed;inset:0;z-index:30;pointer-events:none;display:grid;place-items:center;padding:24px}.rare-notification{width:min(340px,calc(100vw - 48px));padding:20px 24px;border:3px solid #66d9ff;border-radius:14px;background:#202020;box-shadow:0 10px 34px #000b;text-align:center;animation:rare-pop 3.35s ease both}.rare-notification h3{margin:0 0 6px;font-size:28px;color:#66d9ff}.rare-notification .rare-item{font-size:21px;font-weight:700}.rare-notification.super{border-color:#ffcc33}.rare-notification.super h3{color:#ffcc33}.rare-notification.mega{border-color:#ff4dff}.rare-notification.mega h3{color:#ff4dff}.rare-notification.collection{border-color:#ffe26a}.rare-notification.collection h3{color:#ffe26a}.rainbow-text{background:linear-gradient(90deg,#ff5c5c,#ffb347,#fff45c,#68e06f,#5cb8ff,#b783ff,#ff7dc8,#ff5c5c);background-size:300% 100%;-webkit-background-clip:text;background-clip:text;color:transparent;animation:rainbow-shift 2s linear infinite}@keyframes rare-pop{0%{opacity:0;transform:translateY(24px) scale(.55)}8%{opacity:1;transform:translateY(0) scale(1.08)}88%{opacity:1;transform:translateY(0) scale(1)}100%{opacity:0;transform:translateY(-20px) scale(.9)}}@keyframes rainbow-shift{to{background-position:300% 0}}@media(max-width:420px){.loot-meta-grid{grid-template-columns:1fr}}`;
document.head.appendChild(style);

const layer=document.createElement('div');layer.className='rare-notification-layer';document.body.appendChild(layer);
const queue=[];let showing=false;
const chanceText=chance=>chance>=1?`${Math.round(chance*100)}%`:`1/${Math.max(1,Math.round(1/chance)).toLocaleString()}`;
function cumulativeChance(chance,attempts){const value=1-Math.pow(1-Math.min(1,Math.max(0,chance)),Math.max(1,attempts));return `${(value*100).toFixed(2)}%`}
function enqueue(notification){queue.push(notification);showNext()}
function showNext(){if(showing||!queue.length)return;showing=true;const n=queue.shift(),el=document.createElement('div');el.className=`rare-notification ${n.kind||''}`;el.innerHTML=n.html;layer.appendChild(el);setTimeout(()=>{el.remove();showing=false;showNext()},3400)}

window.addEventListener('elderwild-rare-drop',event=>{
  const d=event.detail||{},chance=Number(d.chance)||0;
  let title='RARE DROP!',kind='';
  if(chance<=.0001){title='MEGA RARE DROP!';kind='mega'}else if(chance<=.001){title='SUPER RARE DROP!';kind='super'}
  const rainbow=chance<=.0005?' rainbow-text':'';
  enqueue({kind,html:`<h3>${title}</h3><div class="rare-item${rainbow}">${escapeHtml(d.item||'Item')} × ${Math.max(1,Number(d.quantity)||1)}</div><small>${chanceText(chance)} effective chance</small>`});
});
window.addEventListener('elderwild-collection-complete',event=>{const d=event.detail||{};enqueue({kind:'collection',html:`<h3>COLLECTION LOG COMPLETE!</h3><div class="rare-item">${escapeHtml(d.enemyName||'Enemy')}</div><small>Global drop boost is now ${(Number(d.boostPercent)||0).toFixed(1)}%</small>`})});

function escapeHtml(value){return String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
function getGame(){return window.__elderwildGame}
function enhanceHome(){const game=getGame();if(!game)return;const hero=[...document.querySelectorAll('#view .hero')].find(el=>el.querySelector('h2')?.textContent?.startsWith('Welcome'));if(!hero)return;let panel=document.querySelector('#view .loot-meta-panel');if(!panel){panel=document.createElement('section');panel.className='panel loot-meta-panel';hero.insertAdjacentElement('afterend',panel)}const luck=game.state.luckiestDrop||{},valid=!!luck.itemName&&Number(luck.chance)>0;panel.innerHTML=`<h2>Loot Luck</h2><div class="loot-meta-grid"><div class="loot-meta-card"><strong>${game.totalKills().toLocaleString()}</strong><small>Total enemies killed</small></div><div class="loot-meta-card"><strong>${game.completedCollections()} / ${ENEMIES.length}</strong><small>Completed collections</small></div><div class="loot-meta-card"><strong>${game.globalDropBoostPercent().toFixed(1)}%</strong><small>Global drop boost</small></div></div><div class="luckiest-drop"><strong>Luckiest drop</strong>${valid?`<div>${escapeHtml(luck.itemName)} · ${chanceText(Number(luck.chance))}</div><small>${Math.max(1,Number(luck.attempts)||1).toLocaleString()} ${escapeHtml(luck.source||'attempts')} · cumulative chance ${cumulativeChance(Number(luck.chance),Number(luck.attempts)||1)}</small>`:'<div class="muted">None yet</div>'}</div>`}
function enhanceCollection(){const game=getGame();if(!game)return;const panel=[...document.querySelectorAll('#view .panel')].find(el=>el.querySelector('h2')?.textContent==='Collection Log');if(!panel)return;let banner=panel.querySelector('.pass2-boost-banner');if(!banner){banner=document.createElement('div');banner.className='pass2-boost-banner';const summary=panel.querySelector('.collection-summary');summary?.insertAdjacentElement('afterend',banner)}if(banner)banner.innerHTML=`<strong>Global drop boost: ${game.globalDropBoostPercent().toFixed(1)}%</strong><br><small class="muted">+0.1% for every completed enemy collection</small>`;colorRainbowDrops(panel,game)}
function colorRainbowDrops(panel,game){const cards=[...panel.querySelectorAll('.activity-list>.card')];for(const card of cards){const title=card.querySelector('.skill-row strong')?.textContent||'';const enemy=ENEMIES.find(e=>title.includes(e.name));if(!enemy)continue;const rows=[...card.querySelectorAll('.drop-row')],items=game.collectionItems(enemy);rows.forEach((row,index)=>{const item=items[index],drop=enemy.drops.find(d=>d.item===item);if(!drop||row.classList.contains('unknown'))return;row.classList.toggle('rainbow-text',drop.chance<=.0005)})}}
let queued=false;function enhance(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;enhanceHome();enhanceCollection()})}
new MutationObserver(enhance).observe(document.querySelector('#view'),{childList:true,subtree:true});
window.addEventListener('elderwild-game-state',enhance);enhance();
