import{Game}from'./game.js';
const PORTRAIT_COUNT=25;
const pathFor=index=>`assets/character_portrait_${String(index).padStart(2,'0')}.png`;
const clamp=index=>Math.max(1,Math.min(PORTRAIT_COUNT,Math.round(Number(index)||1)));
const game=()=>window.__elderwildGame;
if(!Game.prototype.__portraitPatched){
  const originalReset=Game.prototype.reset;
  Game.prototype.setPortrait=function(index){this.state.portraitIndex=clamp(index);this.save();this.onChange();window.dispatchEvent(new CustomEvent('elderwild-portrait-changed',{detail:{index:this.state.portraitIndex}}));return this.state.portraitIndex};
  Game.prototype.reset=function(...args){const result=originalReset.apply(this,args);this.state.portraitIndex=1;this.save();this.onChange();return result};
  Game.prototype.__portraitPatched=true;
}
const current=game();if(current&&!current.state.portraitIndex){current.state.portraitIndex=1;current.save()}
const style=document.createElement('style');style.textContent=`.portrait-setting{margin:14px 0;padding:12px;border:1px solid #3d5145;border-radius:10px;background:#121714}.portrait-setting h3{margin:0 0 9px;color:#72d88d}.portrait-picker{display:grid;grid-template-columns:46px minmax(0,1fr) 46px;gap:10px;align-items:center}.portrait-arrow{height:46px;padding:0!important;font-size:24px!important;font-weight:900}.portrait-preview-wrap{text-align:center}.portrait-preview{width:128px;height:128px;max-width:100%;margin:0 auto;border:2px solid #57c879;border-radius:10px;background:#0d1310;overflow:hidden;display:grid;place-items:center}.portrait-preview img{width:100%;height:100%;object-fit:cover;image-rendering:pixelated}.portrait-count{display:block;margin-top:6px;color:#a7b5ab;font-size:11px}.portrait-note{margin-top:7px;color:#91a096;font-size:10px;text-align:center}.home-avatar img,.combat-fighter.player .combat-fighter-art img{width:100%;height:100%;object-fit:cover;image-rendering:pixelated}.home-avatar{overflow:hidden;padding:0!important}.combat-fighter.player .combat-fighter-art{padding:0!important}@media(max-width:360px){.portrait-picker{grid-template-columns:40px minmax(0,1fr) 40px}.portrait-preview{width:112px;height:112px}}`;document.head.append(style);
function decoratePortraits(g){const index=clamp(g.state.portraitIndex),src=pathFor(index);const home=document.querySelector('.home-avatar');if(home&&home.dataset.portrait!==String(index)){home.dataset.portrait=String(index);home.innerHTML=`<img src="${src}" alt="${g.state.playerName} portrait">`}const fighter=document.querySelector('.combat-fighter.player .combat-fighter-art');if(fighter&&fighter.dataset.portrait!==String(index)){fighter.dataset.portrait=String(index);fighter.innerHTML=`<img src="${src}" alt="${g.state.playerName} portrait">`}}
function enhanceSettings(g){const panel=[...document.querySelectorAll('#view .panel')].find(p=>p.querySelector('h2')?.textContent==='Settings');if(!panel)return;let section=panel.querySelector('.portrait-setting');if(!section){section=document.createElement('section');section.className='portrait-setting';const row=panel.querySelector('.settings-row');(row||panel.querySelector('h2'))?.insertAdjacentElement(row?'beforebegin':'afterend',section)}if(section.dataset.boundPortrait===String(g.state.portraitIndex))return;const index=clamp(g.state.portraitIndex);section.dataset.boundPortrait=String(index);section.innerHTML=`<h3>Character Portrait</h3><div class="portrait-picker"><button type="button" class="action-button portrait-arrow" data-portrait-prev aria-label="Previous portrait">‹</button><div class="portrait-preview-wrap"><div class="portrait-preview"><img src="${pathFor(index)}" alt="Portrait ${index} of ${PORTRAIT_COUNT}"></div><span class="portrait-count">Portrait ${String(index).padStart(2,'0')} / ${PORTRAIT_COUNT}</span></div><button type="button" class="action-button portrait-arrow" data-portrait-next aria-label="Next portrait">›</button></div><div class="portrait-note">Your portrait saves automatically with this character.</div>`;section.querySelector('[data-portrait-prev]').onclick=()=>g.setPortrait(index<=1?PORTRAIT_COUNT:index-1);section.querySelector('[data-portrait-next]').onclick=()=>g.setPortrait(index>=PORTRAIT_COUNT?1:index+1)}
let queued=false;function enhance(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;const g=game();if(!g)return;g.state.portraitIndex=clamp(g.state.portraitIndex);decoratePortraits(g);enhanceSettings(g)})}new MutationObserver(enhance).observe(document.body,{childList:true,subtree:true});window.addEventListener('elderwild-game-state',enhance);window.addEventListener('elderwild-save-imported',enhance);window.addEventListener('elderwild-save-restored',enhance);enhance();
