const HP_GREEN=['#21b85a','#58e58c'],HP_ORANGE=['#e99418','#ffc247'],HP_RED=['#d83d3d','#ff6b62'];
const clamp=n=>Math.max(0,Math.min(100,Number(n)||0));
const hpColors=pct=>pct<=20?HP_RED:pct<=40?HP_ORANGE:HP_GREEN;
const gradient=colors=>`linear-gradient(180deg,${colors[1]} 0%,${colors[0]} 48%,${colors[0]} 100%)`;
const style=document.createElement('style');
style.textContent=`.xpbar,.progress-track,.combat-mini-track{position:relative;height:14px!important;border:1px solid #496477!important;border-radius:999px!important;overflow:hidden;background:linear-gradient(180deg,#081117,#101c24)!important;box-shadow:inset 0 1px 3px #000c,0 1px 0 #ffffff12}.xpfill,.progress-fill,.combat-mini-fill{position:relative;height:100%!important;border-radius:999px;transition:width .18s linear,background .18s linear,box-shadow .18s linear!important}.xpfill{background:linear-gradient(180deg,#60A5FA 0%,#3B82F6 52%,#2563EB 100%)!important;box-shadow:inset 0 1px 0 #ffffff66,0 0 6px #3B82F655}.progress-fill{background:linear-gradient(180deg,#A78BFA 0%,#8B5CF6 52%,#7C3AED 100%)!important;box-shadow:inset 0 1px 0 #ffffff55,0 0 6px #8B5CF655}.xpbar:after,.progress-track:after,.combat-mini-track:after{content:'';position:absolute;inset:1px 2px auto;height:35%;border-radius:999px;background:linear-gradient(180deg,#ffffff22,transparent);pointer-events:none}.combat-mini-track{height:10px!important}.hp-dynamic{box-shadow:inset 0 1px 0 #ffffff55,0 0 7px var(--hp-glow,#35d66b55)!important}.home-skill-row{grid-template-columns:24px minmax(0,1fr)!important}.home-skill-xp{display:none!important}.home-inline-gear{margin-left:4px;color:#8fa59a!important;font-size:10px;font-weight:500;white-space:nowrap}`;
document.head.appendChild(style);
function setHp(fill,pct){if(!fill)return;const colors=hpColors(clamp(pct));fill.classList.add('hp-dynamic');fill.style.setProperty('background',gradient(colors),'important');fill.style.setProperty('--hp-glow',`${colors[0]}77`)}
function mainCombatBars(){const game=window.__elderwildGame,c=game?.state?.combat;if(!game||!c?.active)return;const enemy=window.__elderwildEnemies?.find?.(e=>e.name===c.enemyName);const enemyPct=enemy?clamp(c.enemyHP/Math.max(1,enemy.hp)*100):null;const playerPct=clamp(c.playerHP/Math.max(1,game.maxHP?.()||1)*100);for(const bar of document.querySelectorAll('#view .xpbar')){const context=((bar.previousElementSibling?.textContent||'')+' '+(bar.parentElement?.textContent||'')).toLowerCase();const fill=bar.querySelector('.xpfill');if(!fill)continue;if(context.includes('enemy hp')&&enemyPct!==null)setHp(fill,enemyPct);else if(context.includes('your hp')||context.includes('player hp'))setHp(fill,playerPct)}}
function miniCombatBars(){const game=window.__elderwildGame,c=game?.state?.combat;if(!game||!c)return;const player=document.querySelector('#combat-mini-player-fill'),enemyFill=document.querySelector('#combat-mini-enemy-fill');if(player)setHp(player,clamp(c.playerHP/Math.max(1,game.maxHP?.()||1)*100));if(c.active&&enemyFill){const enemy=window.__elderwildEnemies?.find?.(e=>e.name===c.enemyName);if(enemy)setHp(enemyFill,clamp(c.enemyHP/Math.max(1,enemy.hp)*100))}}
function textFallback(){for(const bar of document.querySelectorAll('#view .xpbar')){const fill=bar.querySelector('.xpfill');if(!fill||fill.classList.contains('hp-dynamic'))continue;const text=(bar.parentElement?.textContent||'');const m=text.match(/(?:Enemy HP|Your HP|Player HP)[^\d]*(\d+)\s*\/\s*(\d+)/i);if(m)setHp(fill,Number(m[1])/Math.max(1,Number(m[2]))*100)}}
function alignHomeCombatBars(){for(const row of document.querySelectorAll('.home-skill-row')){const strong=row.querySelector('.home-skill-name strong'),bonus=row.querySelector('.home-skill-xp');if(!strong||!bonus)continue;strong.querySelector('.home-inline-gear')?.remove();const text=(bonus.textContent||'').trim();if(text){const span=document.createElement('span');span.className='home-inline-gear';span.textContent=` (${text})`;strong.appendChild(span)}}}
let queued=false;function apply(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;mainCombatBars();miniCombatBars();textFallback();alignHomeCombatBars()})}
new MutationObserver(apply).observe(document.body,{childList:true,subtree:true,characterData:true});window.addEventListener('elderwild-game-state',apply);setInterval(apply,250);apply();
