const style=document.createElement('style');style.textContent=`.save-tools{margin-top:16px;padding-top:14px;border-top:1px solid #35493d}.save-status{display:grid;gap:4px;padding:9px 10px;margin:10px 0;border:1px solid #35493d;border-radius:8px;background:#121714}.save-status strong{color:#72d88d}.save-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px}.save-actions button{width:100%}.save-file-input{display:none}.save-note{margin-top:8px;font-size:11px;color:#91a096}@media(max-width:420px){.save-actions{grid-template-columns:1fr}}`;document.head.appendChild(style);

const game=()=>window.__elderwildGame;
function fmtTime(ms){if(!ms)return'Never';try{return new Date(ms).toLocaleString()}catch{return'Unknown'}}
function downloadSave(g){const text=g.exportSaveText(),blob=new Blob([text],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`elderwild-save-${new Date().toISOString().slice(0,10)}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function enhance(){const g=game();if(!g)return;const panel=[...document.querySelectorAll('#view .panel')].find(p=>p.querySelector('h2')?.textContent==='Settings');if(!panel||panel.querySelector('.save-tools'))return;
 const old=[...panel.querySelectorAll('p.muted')].find(p=>p.textContent.includes('Older v1 web saves'));if(old)old.textContent='Progress saves automatically in this browser. A last known-good backup is kept locally whenever possible.';
 const section=document.createElement('section');section.className='save-tools';section.innerHTML=`<h3>Save Management</h3><div class="save-status"><strong>Autosave active</strong><span class="muted">Last save: ${fmtTime(g.state.lastSavedAt)}</span><span class="muted">Browser backup: ${g.hasBrowserBackup?.()?'Available':'Not created yet'}</span></div><div class="save-actions"><button class="action-button" data-save-export>Export Save</button><button class="action-button" data-save-import>Import Save</button><button class="action-button" data-save-backup ${g.hasBrowserBackup?.()?'':'disabled'}>Restore Backup</button><button class="action-button" data-save-now>Save Now</button></div><input class="save-file-input" type="file" accept="application/json,.json"><div class="save-note">Exported saves can be moved between browsers/devices. Importing replaces current progress, but the current browser save is backed up first.</div>`;
 const reset=panel.querySelector('#reset-save');reset?.insertAdjacentElement('beforebegin',section);if(!section.isConnected)panel.append(section);
 section.querySelector('[data-save-export]').addEventListener('click',()=>downloadSave(g));
 section.querySelector('[data-save-now]').addEventListener('click',()=>{g.save();alert('Save written successfully.')});
 const input=section.querySelector('.save-file-input');section.querySelector('[data-save-import]').addEventListener('click',()=>input.click());input.addEventListener('change',async()=>{const file=input.files?.[0];if(!file)return;try{const text=await file.text();if(!confirm(`Import ${file.name} and replace current progress?\n\nYour current browser save will be backed up first.`))return;g.importSaveText(text);alert('Save imported successfully.')}catch(err){alert(`Import failed: ${err?.message||err}`)}finally{input.value=''}});
 section.querySelector('[data-save-backup]').addEventListener('click',()=>{if(!confirm('Restore the previous browser backup and replace current progress?'))return;try{g.restoreBackup();alert('Backup restored successfully.')}catch(err){alert(`Restore failed: ${err?.message||err}`)}});
 if(reset){const fresh=reset.cloneNode(true);reset.replaceWith(fresh);fresh.addEventListener('click',()=>{if(!confirm('Reset ALL web progress? This cannot be undone unless you exported a save first.'))return;if(!confirm('Final confirmation: permanently reset this character?'))return;g.reset()})}
 if(sessionStorage.getItem('elderwild-save-recovered')==='1'){sessionStorage.removeItem('elderwild-save-recovered');setTimeout(()=>alert('The primary browser save was damaged, so Elderwild recovered the last known-good backup.'),50)}
}
let queued=false;function queue(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;enhance()})}new MutationObserver(queue).observe(document.querySelector('#view'),{childList:true,subtree:true});window.addEventListener('elderwild-game-state',queue);queue();
