const root=new URL('../',import.meta.url);
const style=document.createElement('style');style.textContent=`body.elderwild-starting{overflow:hidden}.startup-loader{position:fixed;inset:0;z-index:1000;display:grid;place-items:center;padding:22px;background:linear-gradient(#08100bcc,#08100bf0),url('assets/backgrounds/background_landing.png') center/cover no-repeat}.startup-loader-card{width:min(390px,100%);text-align:center}.startup-loader-title{font-size:38px;line-height:1;font-weight:900;letter-spacing:.05em;color:#72d88d;text-shadow:0 3px 8px #000}.startup-loader-subtitle{margin:7px 0 24px;color:#b8c6bc;font-size:12px}.startup-loader-status{min-height:18px;margin-bottom:7px;color:#e8f2eb;font-size:12px}.startup-loader-track{height:12px;padding:2px;border:1px solid #6f3636;border-radius:3px;background:#5b1818;box-shadow:inset 0 2px 5px #0009}.startup-loader-fill{width:0;height:100%;border-radius:1px;background:linear-gradient(180deg,#68df87,#32a952);box-shadow:0 0 8px #46c96966;transition:width .18s ease}.startup-loader-percent{margin-top:6px;color:#8fa096;font-size:10px}`;document.head.append(style);
document.body.classList.add('elderwild-starting');const layer=document.createElement('div');layer.className='startup-loader';layer.innerHTML=`<section class="startup-loader-card"><div class="startup-loader-title">SCAPERUNNER</div><div class="startup-loader-subtitle">Preparing your adventure</div><div class="startup-loader-status">Starting…</div><div class="startup-loader-track"><div class="startup-loader-fill"></div></div><div class="startup-loader-percent">0%</div></section>`;document.body.append(layer);const fill=layer.querySelector('.startup-loader-fill'),status=layer.querySelector('.startup-loader-status'),percent=layer.querySelector('.startup-loader-percent');
export function setProgress(value,label){const p=Math.max(0,Math.min(1,Number(value)||0));fill.style.width=`${Math.round(p*100)}%`;percent.textContent=`${Math.round(p*100)}%`;if(label)status.textContent=label}
async function warm(url){try{const r=await fetch(url,{cache:'force-cache'});return r.ok?r:null}catch{return null}}
async function decode(url){try{const img=new Image();img.src=url;img.decoding='async';await img.decode();return true}catch{return false}}
const pageBackgrounds=['background_landing.png','background_home.png','background_skills.png','background_skill.png','background_combat.png','background_collection_log.png','background_inventory.png','background_settings.png'].map(n=>new URL(`assets/backgrounds/${n}`,root).href);
const tierBackgrounds=['tier_greenvale.png','tier_mirewood.png','tier_frostpeak.png','tier_emberfall.png','tier_sandswept_ruins.png','tier_astral_reach.png','tier_umbral_expanse.png'].map(n=>new URL(`assets/backgrounds/${n}`,root).href);
const skills=['agility','attack','crafting','defense','farming','fishing','fletching','hp','mining','strength','thieving','woodcutting'].map(n=>new URL(`assets/skills/skill_${n}.png`,root).href);
const portraits=Array.from({length:25},(_,i)=>new URL(`assets/character_portrait_${String(i+1).padStart(2,'0')}.png`,root).href);
function idleWarm(urls){const run=()=>Promise.allSettled(urls.map(warm));if('requestIdleCallback'in window)requestIdleCallback(run,{timeout:2500});else setTimeout(run,500)}
export async function preloadAssets(){setProgress(.18,'Preparing sprite manifest');let manifest=null;try{const r=await warm(new URL('assets/sprite-manifest.json',root).href);if(r)manifest=await r.json()}catch{}window.__elderwildPreloadCache={...(window.__elderwildPreloadCache||{}),manifest,pageBackgrounds,tierBackgrounds,skills,portraits};setProgress(.30,'Warming sprite atlases');if(manifest){const atlas=[];for(const key of['enemies','items'])if(manifest[key]?.image)atlas.push(new URL(manifest[key].image,root).href);await Promise.allSettled(atlas.map(decode));window.__elderwildPreloadCache.atlases=atlas}setProgress(.50,'Preparing page artwork');await Promise.allSettled(pageBackgrounds.map(warm));setProgress(.65,'Preparing skill artwork');await Promise.allSettled(skills.map(warm));setProgress(.74,'Preparing reusable assets');idleWarm([...tierBackgrounds,...portraits])}
export async function finish(){setProgress(1,'Ready');await new Promise(r=>setTimeout(r,90));layer.remove();document.body.classList.remove('elderwild-starting');window.dispatchEvent(new CustomEvent('elderwild-startup-ready'))}
